# Case studies built only from public sources. Each string is a (fr, en) pair.

CASES = [
 {
  "path": "case-studies/tsb-2018.html",
  "sector": ("Finance", "Finance"),
  "short": ("TSB : une migration informatique qui paralyse une banque", "TSB: an IT migration that paralysed a bank"),
  "summary": ("Royaume-Uni, 2018. Une migration de plateforme bancaire échoue dès sa mise en service et perturbe les services pendant des mois.",
              "UK, 2018. A banking platform migration fails at go-live and disrupts services for months."),
  "facts": [
    (("Secteur", "Sector"), ("Banque de détail", "Retail banking")),
    (("Pays", "Country"), ("Royaume-Uni", "United Kingdom")),
    (("Date", "Date"), ("Avril 2018", "April 2018")),
    (("Durée", "Duration"), ("Retour à la normale en décembre 2018", "Business as usual only by December 2018")),
    (("Conséquences réglementaires", "Regulatory outcome"), ("Amende de 48,65 M£ (FCA et PRA, 2022)", "£48.65m fine (FCA and PRA, 2022)")),
  ],
  "timeline": [
    (("2015–2018", "2015–2018"), ("TSB prépare le transfert de ses services de la plateforme de Lloyds vers une nouvelle plateforme conçue et exploitée par une filiale de sa société mère, Sabadell.",
                                  "TSB prepares to move its services from the Lloyds platform to a new platform designed and run by a subsidiary of its parent, Sabadell.")),
    (("20–22 avril 2018", "20–22 April 2018"), ("Les données sont migrées avec succès, mais la plateforme connaît des défaillances techniques dès sa mise en service.",
                                  "The data migrates successfully, but the platform suffers technical failures as soon as it goes live.")),
    (("Semaines suivantes", "Following weeks"), ("Les agences, le téléphone, les services en ligne et mobiles sont perturbés ; toutes les agences et une part importante des 5,2 millions de clients sont touchées.",
                                  "Branch, telephone, online and mobile banking are disrupted; every branch and a large share of 5.2 million customers are affected.")),
    (("Décembre 2018", "December 2018"), ("La banque revient à un fonctionnement normal.", "The bank returns to business as usual.")),
    (("Décembre 2022", "December 2022"), ("La FCA et la PRA infligent une amende de 48,65 M£. En 2023, la PRA sanctionne aussi l'ancien directeur informatique.",
                                  "The FCA and PRA impose a £48.65m fine. In 2023 the PRA also fines the former CIO.")),
  ],
  "wrong": [
    (("Un calendrier fixé à l'envers", "A schedule worked backwards"), ("Selon les régulateurs, le plan partait d'une date cible au lieu d'estimer de façon réaliste la durée de chaque étape, même après des retards.",
                                  "According to the regulators, the plan worked back from a target date instead of realistically estimating each stage, even after delays.")),
    (("Des tests réduits", "Reduced testing"), ("La portée des tests non fonctionnels des canaux numériques a été ramenée à un seul des deux centres de données.",
                                  "The scope of non-functional testing for digital channels was reduced to one of the two data centres.")),
    (("Une supervision insuffisante du fournisseur", "Weak supplier oversight"), ("Les régulateurs ont conclu que la banque n'avait pas géré adéquatement les risques liés à son fournisseur informatique externalisé, même intra-groupe.",
                                  "The regulators concluded the bank did not adequately manage the risks of its outsourced IT supplier, even though it was within the group.")),
  ],
  "lessons": [
    (("Planifier de gauche à droite", "Plan left to right"), ("Estimer chaque phase avant de fixer une date, et réévaluer honnêtement après chaque retard.", "Estimate each phase before setting a date, and honestly reassess after every delay."), "what-we-do/services/assessments.html"),
    (("Tester dans des conditions réelles", "Test under real conditions"), ("Charge, capacité et bascule sur tous les centres de données avant la mise en service, avec un plan de retour arrière éprouvé.", "Load, capacity and failover across every data centre before go-live, with a proven rollback plan."), "what-we-do/services/exercises.html"),
    (("Superviser les tiers critiques", "Oversee critical third parties"), ("Un fournisseur intra-groupe reste un tiers : exiger des preuves, pas des assurances. C'est aussi une exigence de DORA et des règles FCA/PRA.", "An intra-group supplier is still a third party: ask for evidence, not reassurance. DORA and FCA/PRA rules require it too."), "what-we-do/regulations.html"),
  ],
  "sources": [
    ("Bank of England / PRA — TSB fined for operational resilience failings (2022)", "https://www.bankofengland.co.uk/news/2022/december/tsb-fined-for-operational-resilience-failings"),
    ("Geldards — TSB fined £48.65m by the FCA and PRA", "https://www.geldards.com/insights/tsb-fined-48-65m-by-the-fca-and-pra-for-operational-resilience-failings/"),
    ("Taylor Wessing — Ex-CIO fined for bank IT migration failures", "https://www.taylorwessing.com/en/insights-and-events/insights/2023/05/ex-cio-fined-for-bank-it-migration-failures"),
  ],
 },
 {
  "path": "case-studies/colonial-pipeline-2021.html",
  "sector": ("Énergie", "Energy"),
  "short": ("Colonial Pipeline : un rançongiciel qui coupe le carburant", "Colonial Pipeline: ransomware that cut the fuel supply"),
  "summary": ("États-Unis, 2021. Un mot de passe VPN compromis mène à l'arrêt du plus grand oléoduc de produits raffinés du pays.",
              "United States, 2021. A compromised VPN password leads to the shutdown of the country's largest refined-fuel pipeline."),
  "facts": [
    (("Secteur", "Sector"), ("Transport de carburant", "Fuel transport")),
    (("Pays", "Country"), ("États-Unis", "United States")),
    (("Date", "Date"), ("Mai 2021", "May 2021")),
    (("Durée", "Duration"), ("Oléoduc arrêté du 7 au 12 mai", "Pipeline stopped 7–12 May")),
    (("Rançon", "Ransom"), ("Environ 4,4 M$ (2,3 M$ récupérés)", "About $4.4m ($2.3m recovered)")),
  ],
  "timeline": [
    (("29 avril 2021", "29 April 2021"), ("Les attaquants accèdent au réseau informatique de l'entreprise, neuf jours avant l'attaque.", "Attackers gain access to the company's IT network, nine days before the attack.")),
    (("7 mai 2021", "7 May 2021"), ("Un opérateur découvre une note de rançon. L'entreprise arrête l'ensemble de ses 5 500 miles d'oléoduc par précaution, bien que les systèmes opérationnels n'aient pas été directement touchés.",
                                     "An operator finds a ransom note. The company shuts down its entire 5,500-mile pipeline as a precaution, even though operational systems were not directly hit.")),
    (("7 mai 2021", "7 May 2021"), ("L'entreprise paie une rançon d'environ 4,4 M$ en bitcoins pour obtenir un outil de déchiffrement.", "The company pays a ransom of about $4.4m in bitcoin for a decryption tool.")),
    (("12 mai 2021", "12 May 2021"), ("Redémarrage de l'oléoduc, après des pénuries de carburant et des hausses de prix sur la côte Est.", "The pipeline restarts, after fuel shortages and price spikes on the East Coast.")),
    (("7 juin 2021", "7 June 2021"), ("Le département de la Justice annonce avoir récupéré environ 2,3 M$ de la rançon.", "The Justice Department announces it recovered about $2.3m of the ransom.")),
  ],
  "wrong": [
    (("Un accès distant mal protégé", "Poorly protected remote access"), ("L'accès initial s'est fait par un mot de passe VPN compromis, sur un compte qui, selon les rapports publics, n'avait pas d'authentification multifacteur et n'était plus utilisé.",
                                  "Initial access came through a compromised VPN password, on an account that, according to public reports, had no multi-factor authentication and was no longer in use.")),
    (("Une frontière TI/OT incertaine", "An uncertain IT/OT boundary"), ("Faute de certitude sur l'étendue de la compromission, l'entreprise a arrêté l'exploitation physique alors que seul le réseau informatique était touché.",
                                  "Without certainty about the extent of the compromise, the company stopped physical operations although only the IT network was hit.")),
    (("Une reprise dépendante de la rançon", "Recovery dependent on the ransom"), ("La rançon a été payée pour accélérer la reprise, signe que la restauration à partir de sauvegardes ne suffisait pas à tenir les délais voulus.",
                                  "The ransom was paid to speed up recovery, a sign that restoring from backups alone could not meet the required timeframe.")),
  ],
  "lessons": [
    (("MFA sur tous les accès distants", "MFA on every remote access"), ("Et suppression régulière des comptes inactifs, surtout ceux qui ouvrent un accès VPN.", "And regular removal of inactive accounts, especially those with VPN access."), "what-we-do/expertise/cybersecurity.html"),
    (("Segmenter et connaître ses dépendances", "Segment and know your dependencies"), ("Savoir à l'avance si l'exploitation peut continuer quand l'informatique est isolée, et selon quels critères arrêter.", "Know in advance whether operations can continue when IT is isolated, and on what criteria to stop."), "what-we-do/expertise/business-continuity.html"),
    (("Pouvoir restaurer sans payer", "Be able to restore without paying"), ("Des sauvegardes isolées et des restaurations testées donnent le choix de ne pas négocier.", "Isolated backups and tested restores give you the choice not to negotiate."), "what-we-do/expertise/disaster-recovery.html"),
  ],
  "sources": [
    ("U.S. Department of Energy — Colonial Pipeline Cyber Incident", "https://www.energy.gov/ceser/colonial-pipeline-cyber-incident"),
    ("Idaho National Laboratory — CyOTE case study: DarkSide ransomware attack on Colonial Pipeline", "https://cyote.inl.gov/content/uploads/24/2025/12/CyOTE-Case-Study_Colonial-Pipeline.pdf"),
    ("Kennedys — Multi-million dollars recovered from Colonial Pipeline ransomware attackers", "https://www.kennedyslaw.com/en/thought-leadership/article/cyber-recoveries-multi-million-dollars-recovered-from-colonial-pipeline-ransomware-attackers/"),
  ],
 },
 {
  "path": "case-studies/marks-and-spencer-2025.html",
  "sector": ("Commerce de détail", "Retail"),
  "short": ("Marks & Spencer : des semaines sans commerce en ligne", "Marks & Spencer: weeks without online sales"),
  "summary": ("Royaume-Uni, 2025. Une cyberattaque interrompt les commandes en ligne et force les magasins à fonctionner manuellement.",
              "UK, 2025. A cyberattack halts online orders and forces stores onto manual processes."),
  "facts": [
    (("Secteur", "Sector"), ("Commerce de détail", "Retail")),
    (("Pays", "Country"), ("Royaume-Uni", "United Kingdom")),
    (("Date", "Date"), ("Avril 2025", "April 2025")),
    (("Durée", "Duration"), ("Commandes en ligne suspendues du 25 avril au 10 juin", "Online orders paused from 25 April to 10 June")),
    (("Impact estimé", "Estimated impact"), ("Environ 300 M£ sur le bénéfice annuel, avant assurance", "About £300m on annual profit, before insurance")),
  ],
  "timeline": [
    (("Vers le 21 avril 2025", "Around 21 April 2025"), ("Pendant le week-end de Pâques, les paiements sans contact et le retrait en magasin sont perturbés.", "Over the Easter weekend, contactless payments and click and collect are disrupted.")),
    (("22 avril 2025", "22 April 2025"), ("L'entreprise déclare un incident de cybersécurité à la Bourse de Londres.", "The company discloses a cyber incident to the London Stock Exchange.")),
    (("25 avril 2025", "25 April 2025"), ("Les commandes sur le site et l'application sont suspendues. Les magasins restent ouverts, avec des processus manuels et des ruptures de stock.",
                                         "Website and app orders are paused. Stores stay open, with manual processes and stock shortages.")),
    (("13 mai 2025", "13 May 2025"), ("L'entreprise confirme le vol de données personnelles de clients, sans données de carte de paiement ni mots de passe.", "The company confirms theft of customer personal data, with no payment card details or passwords.")),
    (("21 mai 2025", "21 May 2025"), ("L'impact est estimé à environ 300 M£ sur le bénéfice de l'exercice.", "The impact is estimated at about £300m on the year's profit.")),
    (("10 juin 2025", "10 June 2025"), ("Reprise des commandes en ligne avec livraison ; le retrait en magasin ne revient que plusieurs semaines plus tard.", "Online orders for delivery resume; click and collect returns only weeks later.")),
  ],
  "wrong": [
    (("L'humain comme porte d'entrée", "People as the way in"), ("Selon les informations publiées, les attaquants auraient obtenu l'accès par ingénierie sociale auprès d'un centre de services informatiques tiers.",
                                  "According to published reports, the attackers gained access by social engineering a third-party IT help desk.")),
    (("Une présence non détectée", "Undetected presence"), ("Des rapports indiquent que l'accès initial remonterait à février 2025, soit plusieurs semaines avant l'attaque visible.",
                                  "Reports indicate initial access may date back to February 2025, several weeks before the visible attack.")),
    (("Des systèmes très interdépendants", "Tightly coupled systems"), ("Commandes, paiements, stocks et logistique ont été touchés ensemble, ce qui a rendu la reprise longue et progressive.",
                                  "Orders, payments, stock and logistics were hit together, which made recovery long and gradual.")),
  ],
  "lessons": [
    (("Protéger le centre de services", "Protect the help desk"), ("Vérification d'identité renforcée avant toute réinitialisation de mot de passe ou de MFA, y compris chez les prestataires.", "Strong identity checks before any password or MFA reset, including at service providers."), "what-we-do/expertise/cybersecurity.html"),
    (("Prévoir le mode dégradé", "Plan for degraded mode"), ("Des procédures manuelles préparées pour les magasins, les stocks et la chaîne d'approvisionnement.", "Prepared manual procedures for stores, stock and the supply chain."), "what-we-do/expertise/business-continuity.html"),
    (("Répéter la reprise par étapes", "Rehearse staged recovery"), ("Définir l'ordre de rétablissement des services et l'exercer avant l'incident.", "Define the order in which services come back and rehearse it before an incident."), "what-we-do/services/exercises.html"),
  ],
  "sources": [
    ("The Register — M&S stops online orders as 'cyber incident' issues worsen", "https://www.theregister.com/2025/04/25/ms_halts_online_orders/"),
    ("Al Jazeera / AP — UK retailer M&S puts cyberattack cost at $400m", "https://www.aljazeera.com/economy/2025/5/21/uk-retailer-ms-puts-cyberattack-cost-at-400m-as-disruptions-continue"),
    ("TechRadar — Marks and Spencer click and collect is back", "https://www.techradar.com/pro/security/marks-and-spencer-click-and-collect-is-back-at-last-services-return-following-cyber-incident"),
    ("BlackFog — Marks & Spencer breach timeline", "https://www.blackfog.com/marks-and-spencer-ransomware-attack/"),
  ],
 },
]

CASES += [
 {
  "path": "case-studies/change-healthcare-2024.html",
  "sector": ("Santé", "Healthcare"),
  "short": ("Change Healthcare : un portail sans MFA paralyse la facturation médicale", "Change Healthcare: one portal without MFA stalls US medical billing"),
  "summary": ("États-Unis, 2024. Un rançongiciel frappe un intermédiaire central du système de santé et perturbe pharmacies et prestataires pendant des mois.",
              "United States, 2024. Ransomware hits a central intermediary of the healthcare system and disrupts pharmacies and providers for months."),
  "facts": [
    (("Secteur", "Sector"), ("Traitement des transactions de santé", "Healthcare transaction processing")),
    (("Pays", "Country"), ("États-Unis", "United States")),
    (("Date", "Date"), ("Février 2024", "February 2024")),
    (("Personnes touchées", "People affected"), ("Environ 192,7 millions (estimation de 2025)", "About 192.7 million (2025 estimate)")),
    (("Rançon", "Ransom"), ("22 M$ payés, sans empêcher une seconde extorsion", "$22m paid, without preventing a second extortion")),
  ],
  "timeline": [
    (("12 février 2024", "12 February 2024"), ("Des attaquants se connectent à un portail d'accès distant Citrix avec des identifiants compromis. Le portail n'exigeait pas d'authentification multifacteur.", "Attackers log in to a Citrix remote access portal with compromised credentials. The portal did not require multi-factor authentication.")),
    (("12–21 février 2024", "12–21 February 2024"), ("Ils se déplacent dans le réseau et exfiltrent des données pendant environ neuf jours.", "They move through the network and exfiltrate data for about nine days.")),
    (("21 février 2024", "21 February 2024"), ("Le rançongiciel est déployé. L'entreprise coupe ses centres de données, ce qui interrompt les échanges électroniques entre prestataires, assureurs et pharmacies.", "Ransomware is deployed. The company shuts down its data centres, halting electronic exchanges between providers, payers and pharmacies.")),
    (("Mars–avril 2024", "March–April 2024"), ("Une rançon de 22 M$ est payée. Un affilié conserve pourtant les données et une seconde extorsion est lancée par un autre groupe.", "A $22m ransom is paid. An affiliate nevertheless keeps the data, and a second extortion is launched by another group.")),
    (("Mai 2024", "May 2024"), ("Le PDG de la société mère témoigne devant le Congrès et confirme l'absence de MFA sur le portail.", "The parent company's CEO testifies before Congress and confirms MFA was missing on the portal.")),
  ],
  "wrong": [
    (("Une exception à la règle", "An exception to the rule"), ("Selon le témoignage du PDG, la MFA était une règle de l'entreprise pour les systèmes exposés, mais ce portail y échappait.", "According to the CEO's testimony, MFA was company policy for external systems, but this portal was an exception.")),
    (("Un acteur trop central", "Too central a player"), ("L'entreprise traite une part majeure des transactions de santé américaines : sa panne est devenue celle de tout un secteur.", "The company processes a major share of US healthcare transactions: its outage became an outage for a whole sector.")),
    (("Payer ne protège pas", "Paying doesn't protect you"), ("La rançon n'a pas empêché la conservation des données ni une nouvelle extorsion.", "The ransom did not stop the data from being kept, nor a new extortion attempt.")),
  ],
  "lessons": [
    (("Vérifier, pas supposer", "Verify, don't assume"), ("Contrôler régulièrement que chaque accès exposé applique réellement la MFA, y compris après une acquisition.", "Regularly check that every exposed access point really enforces MFA, including after an acquisition."), "what-we-do/expertise/cybersecurity.html"),
    (("Prévoir la perte d'un intermédiaire", "Plan for losing an intermediary"), ("Identifier les fournisseurs dont la panne bloquerait votre activité et préparer des solutions de repli.", "Identify suppliers whose outage would stop your business and prepare fallbacks."), "what-we-do/expertise/business-continuity.html"),
    (("Planifier la reprise sans rançon", "Plan recovery without a ransom"), ("Des sauvegardes isolées et testées sont la seule garantie de reprise.", "Isolated, tested backups are the only guarantee of recovery."), "what-we-do/expertise/disaster-recovery.html"),
  ],
  "sources": [
    ("TechTarget — Change Healthcare breached via Citrix portal with no MFA", "https://www.techtarget.com/searchsecurity/news/366582824/Change-Healthcare-breached-via-Citrix-portal-with-no-MFA"),
    ("Nixon Peabody — The Change Healthcare cybersecurity breach: impact on providers", "https://www.nixonpeabody.com/insights/alerts/2025/11/12/change-healthcare-cybersecurity-breach-impact-on-healthcare-providers"),
    ("HIPAA Journal — Change Healthcare responding to cyberattack", "https://www.hipaajournal.com/change-healthcare-responding-to-cyberattack/"),
  ],
 },
 {
  "path": "case-studies/norsk-hydro-2019.html",
  "sector": ("Industrie", "Manufacturing"),
  "short": ("Norsk Hydro : produire à la main plutôt que payer", "Norsk Hydro: producing by hand rather than paying"),
  "summary": ("Norvège, 2019. Un rançongiciel touche tout le groupe ; l'entreprise refuse de payer, passe en mode manuel et communique ouvertement.",
              "Norway, 2019. Ransomware hits the whole group; the company refuses to pay, switches to manual operations and communicates openly."),
  "facts": [
    (("Secteur", "Sector"), ("Aluminium et énergie", "Aluminium and energy")),
    (("Pays", "Country"), ("Norvège, 40 pays touchés", "Norway, 40 countries affected")),
    (("Date", "Date"), ("Mars 2019", "March 2019")),
    (("Coût estimé", "Estimated cost"), ("650 à 750 M NOK (environ 70 M$)", "NOK 650–750m (about $70m)")),
    (("Rançon", "Ransom"), ("Non payée", "Not paid")),
  ],
  "timeline": [
    (("Avant l'attaque", "Before the attack"), ("Selon une analyse publique, les attaquants entrent par un courriel d'hameçonnage envoyé depuis un compte client usurpé.", "According to a public analysis, the attackers get in through a phishing email sent from a spoofed customer account.")),
    (("19 mars 2019", "19 March 2019"), ("Le rançongiciel LockerGoga chiffre des milliers de serveurs et de postes. Des lignes de production s'arrêtent, d'autres passent en mode manuel.", "LockerGoga ransomware encrypts thousands of servers and PCs. Some production lines stop, others switch to manual operation.")),
    (("Premiers jours", "First days"), ("Les employés travaillent avec papier et crayon ; des retraités reviennent aider sur les procédures papier.", "Staff work with pen and paper; retirees come back to help with paper-based procedures.")),
    (("Semaines suivantes", "Following weeks"), ("L'entreprise reconstruit à partir de sauvegardes et publie des mises à jour quotidiennes. La division Extruded Solutions est la plus touchée.", "The company rebuilds from backups and publishes daily updates. The Extruded Solutions division is hit hardest.")),
    (("2020", "2020"), ("Le rapport annuel estime le coût total entre 650 et 750 M NOK.", "The annual report puts the total cost at NOK 650–750m.")),
  ],
  "wrong": [
    (("Une propagation par l'annuaire", "Spread through the directory"), ("Des analyses publiques indiquent que les attaquants ont obtenu des droits d'administration du domaine et se sont servis de l'annuaire Active Directory pour se propager.", "Public analyses indicate the attackers gained domain admin rights and used Active Directory to spread.")),
    (("Des activités dépendantes de l'informatique", "Operations that depended on IT"), ("Sans accès aux carnets de commandes et aux plannings, les usines d'extrusion ne pouvaient plus livrer.", "Without order books and production schedules, the extrusion plants could not ship.")),
  ],
  "lessons": [
    (("Un mode manuel prêt à l'emploi", "A ready-to-use manual mode"), ("Documenter et exercer les procédures dégradées qui permettent de continuer à produire.", "Document and rehearse the degraded procedures that keep production going."), "what-we-do/expertise/business-continuity.html"),
    (("Protéger et savoir reconstruire l'annuaire", "Protect and be able to rebuild the directory"), ("Les comptes à privilèges et la reprise de l'Active Directory méritent un plan dédié.", "Privileged accounts and Active Directory recovery deserve a dedicated plan."), "what-we-do/expertise/disaster-recovery.html"),
    (("La transparence comme stratégie", "Transparency as a strategy"), ("Des communications préparées et régulières préservent la confiance des clients et des marchés.", "Prepared, regular communication preserves the trust of customers and markets."), "what-we-do/services/exercises.html"),
  ],
  "sources": [
    ("Microsoft — Hackers hit Norsk Hydro with ransomware. The company responded with transparency", "https://news.microsoft.com/source/features/digital-transformation/hackers-hit-norsk-hydro-ransomware-company-responded-transparency/"),
    ("Idaho National Laboratory — CyOTE case study: LockerGoga attack on Norsk Hydro", "https://cyote.inl.gov/content/uploads/24/2025/12/CyOTE-Case-Study_Norsk-Hydro.pdf"),
    ("Control Engineering — Norsk Hydro gets hit by LockerGoga ransomware", "https://www.controleng.com/throwback-attack-norsk-hydro-gets-hit-by-lockergoga-ransomware/"),
  ],
 },
 {
  "path": "case-studies/crowdstrike-delta-2024.html",
  "sector": ("Transport aérien", "Aviation"),
  "short": ("Panne CrowdStrike : quand une mise à jour cloue les avions au sol", "The CrowdStrike outage: when one update grounds the planes"),
  "summary": ("Monde, 2024. Une mise à jour défectueuse d'un logiciel de sécurité fait planter 8,5 millions de postes Windows. Delta met cinq jours à s'en remettre.",
              "Worldwide, 2024. A faulty security software update crashes 8.5 million Windows devices. Delta takes five days to recover."),
  "facts": [
    (("Secteur", "Sector"), ("Transport aérien et tous secteurs", "Aviation and all sectors")),
    (("Portée", "Scope"), ("Mondiale", "Worldwide")),
    (("Date", "Date"), ("19 juillet 2024", "19 July 2024")),
    (("Postes touchés", "Devices affected"), ("Environ 8,5 millions (estimation de Microsoft)", "About 8.5 million (Microsoft estimate)")),
    (("Nature", "Nature"), ("Erreur logicielle, pas une cyberattaque", "Software error, not a cyberattack")),
  ],
  "timeline": [
    (("19 juillet 2024, 04 h 09 UTC", "19 July 2024, 04:09 UTC"), ("CrowdStrike publie une mise à jour de configuration contenant une erreur logique pour son capteur Falcon sur Windows.", "CrowdStrike releases a configuration update containing a logic error for its Falcon sensor on Windows.")),
    (("05 h 27 UTC", "05:27 UTC"), ("La mise à jour est retirée, mais les postes déjà touchés restent bloqués et doivent souvent être réparés un par un.", "The update is pulled, but machines already hit stay down and often have to be fixed one by one.")),
    (("19 juillet", "19 July"), ("Compagnies aériennes, banques, hôpitaux et services d'urgence sont perturbés ; des milliers de vols sont annulés.", "Airlines, banks, hospitals and emergency services are disrupted; thousands of flights are cancelled.")),
    (("19–24 juillet", "19–24 July"), ("Delta indique avoir annulé environ 7 000 vols touchant 1,3 million de passagers, pour un coût d'environ 500 M$.", "Delta says it cancelled about 7,000 flights affecting 1.3 million passengers, at a cost of about $500m.")),
    (("Octobre 2024", "October 2024"), ("Delta poursuit CrowdStrike en justice ; CrowdStrike conteste sa responsabilité.", "Delta sues CrowdStrike; CrowdStrike disputes responsibility.")),
  ],
  "wrong": [
    (("Un déploiement simultané partout", "Deployed everywhere at once"), ("La mise à jour a atteint tous les postes concernés en même temps, sans déploiement progressif permettant de détecter l'erreur.", "The update reached all affected machines at once, with no staged rollout to catch the error.")),
    (("Une réparation manuelle à grande échelle", "Manual repair at scale"), ("Beaucoup de postes devaient être redémarrés en mode sans échec, parfois avec leur clé BitLocker, un par un.", "Many machines had to be booted into safe mode, sometimes with their BitLocker key, one by one.")),
    (("Des reprises très inégales", "Very uneven recoveries"), ("Certaines compagnies ont repris en un jour, d'autres en plusieurs, selon la capacité de leurs systèmes d'exploitation aérienne à rattraper le retard.", "Some airlines recovered in a day, others took several, depending on how well their operational systems could catch up.")),
  ],
  "lessons": [
    (("Traiter les éditeurs comme des dépendances critiques", "Treat vendors as critical dependencies"), ("Un outil de sécurité installé partout est aussi un point de défaillance unique.", "A security tool installed everywhere is also a single point of failure."), "what-we-do/expertise/cloud-resilience.html"),
    (("Prévoir la reprise à grande échelle", "Plan recovery at scale"), ("Accès aux clés de récupération, procédures de masse et personnel mobilisable doivent être prêts.", "Access to recovery keys, mass procedures and staff you can mobilize must be ready."), "what-we-do/expertise/disaster-recovery.html"),
    (("Tester le rattrapage opérationnel", "Test operational catch-up"), ("Au-delà des systèmes, exercer la capacité à reprogrammer équipages, stocks ou rendez-vous après la panne.", "Beyond systems, rehearse your ability to reschedule crews, stock or appointments after the outage."), "what-we-do/services/exercises.html"),
  ],
  "sources": [
    ("Computer Weekly — CrowdStrike update affected 8.5 million Windows devices", "https://www.computerweekly.com/news/366596373/CrowdStrike-update-snafu-affected-85-million-Windows-devices"),
    ("TechTarget — CrowdStrike outage explained", "https://www.techtarget.com/whatis/feature/Explaining-the-largest-IT-outage-in-history-and-whats-next"),
    ("Deccan Herald / Reuters — CrowdStrike executive apologizes before US Congress", "https://www.deccanherald.com/amp/story/business%2Fcompanies%2Fcrowdstrike-executive-apologizes-before-us-congress-for-software-glitch-behind-july-microsoft-outage-3205534"),
  ],
 },
]
