# Page content for the FZ Consultation site. Every string is a (fr, en) pair.

EXPERTISE = [
 {
  "path": "what-we-do/expertise/business-continuity.html",
  "short": ("Continuité des activités", "Business continuity"),
  "summary": ("Garder les services essentiels en marche quand les personnes, les locaux ou les fournisseurs font défaut.",
              "Keep essential services running when people, sites or suppliers are unavailable."),
  "title": ("Continuité des activités", "Business continuity"),
  "lede": ("Savoir ce qui doit continuer, dans quel ordre et avec qui, avant que la crise ne commence.",
           "Know what must keep going, in what order and with whom, before the crisis starts."),
  "intro": ("Un plan de continuité utile ne se limite pas à l'informatique. Il couvre les personnes, les locaux, les fournisseurs et la communication. Nous partons de vos services essentiels et remontons jusqu'aux dépendances qui peuvent les interrompre.",
            "A useful continuity plan is not only about IT. It covers people, sites, suppliers and communication. We start from your essential services and work back to the dependencies that can interrupt them."),
  "cover": [
    (("Analyse d'impact sur les activités", "Business impact analysis"),
     ("Quantifier l'effet d'une interruption dans le temps et fixer les délais de reprise acceptables.", "Quantify how an interruption hurts over time and set acceptable recovery times.")),
    (("Cartographie des dépendances", "Dependency mapping"),
     ("Relier chaque service essentiel aux équipes, systèmes, sites et fournisseurs dont il dépend.", "Link each essential service to the teams, systems, sites and suppliers it relies on.")),
    (("Plans de continuité", "Continuity plans"),
     ("Des plans courts et actionnables, alignés sur ISO 22301 lorsque c'est pertinent.", "Short, actionable plans, aligned with ISO 22301 where relevant.")),
    (("Gestion de crise et communication", "Crisis management and communication"),
     ("Rôles, chaîne de décision et messages préparés pour les employés, clients et régulateurs.", "Roles, decision chain and prepared messages for staff, clients and regulators.")),
    (("Fournisseurs critiques", "Critical suppliers"),
     ("Évaluer la résilience de vos fournisseurs clés et prévoir des solutions de rechange.", "Assess the resilience of key suppliers and plan alternatives.")),
  ],
  "deliverables": [("Rapport d'analyse d'impact", "Business impact analysis report"),
                   ("Registre des services essentiels et dépendances", "Register of essential services and dependencies"),
                   ("Plan de continuité et plan de gestion de crise", "Continuity plan and crisis management plan"),
                   ("Modèles de communication de crise", "Crisis communication templates")],
  "faq": [
    (("Quelle est la différence entre continuité des activités et reprise après sinistre ?", "What is the difference between business continuity and disaster recovery?"),
     ("La continuité des activités vise à maintenir l'organisation en fonctionnement dans son ensemble. La reprise après sinistre en est une partie : elle porte sur le rétablissement des systèmes et des données.",
      "Business continuity is about keeping the whole organization operating. Disaster recovery is one part of it, focused on restoring systems and data.")),
    (("À quelle fréquence faut-il mettre à jour un plan ?", "How often should a plan be updated?"),
     ("Au minimum une fois par an, et après tout changement important : nouveau système, nouveau fournisseur, réorganisation ou incident réel.",
      "At least once a year, and after any significant change: a new system, a new supplier, a reorganization or a real incident.")),
  ],
  "related": ["what-we-do/expertise/disaster-recovery.html", "what-we-do/services/exercises.html"],
 },
 {
  "path": "what-we-do/expertise/disaster-recovery.html",
  "short": ("Reprise après sinistre", "Disaster recovery"),
  "summary": ("Restaurer systèmes et données dans les délais que l'entreprise peut se permettre.",
              "Restore systems and data within the time the business can afford."),
  "title": ("Reprise après sinistre", "Disaster recovery"),
  "lede": ("Une reprise qui fonctionne le jour où vous en avez besoin, pas seulement sur papier.",
           "Recovery that works on the day you need it, not just on paper."),
  "intro": ("Nous fixons avec vous des cibles RTO et RPO réalistes, puis nous concevons, documentons et vérifions la façon de les atteindre, que vos systèmes soient sur site, dans le nuage ou hybrides.",
            "We work with you to set realistic RTO and RPO targets, then design, document and verify how to meet them, whether your systems are on-premises, in the cloud or hybrid."),
  "cover": [
    (("Cibles RTO et RPO", "RTO and RPO targets"),
     ("Des objectifs par service, fondés sur l'impact réel et non sur des moyennes du secteur.", "Targets per service, based on real impact rather than industry averages.")),
    (("Architecture de reprise", "Recovery architecture"),
     ("Revue et conception de sites secondaires, de réplication et de reprise infonuagique.", "Review and design of secondary sites, replication and cloud recovery.")),
    (("Stratégie de sauvegarde", "Backup strategy"),
     ("Copies isolées et immuables, résistantes aux rançongiciels, avec restaurations vérifiées.", "Isolated, immutable copies that resist ransomware, with verified restores.")),
    (("Procédures de reprise", "Recovery runbooks"),
     ("Des étapes précises, ordonnées selon les dépendances, utilisables par une équipe sous pression.", "Precise steps, ordered by dependency, usable by a team under pressure.")),
    (("Tests de reprise", "Recovery testing"),
     ("Restaurations et basculements réels pour mesurer l'écart avec vos cibles.", "Real restores and failovers to measure the gap to your targets.")),
  ],
  "deliverables": [("Cibles RTO et RPO validées par la direction", "RTO and RPO targets signed off by leadership"),
                   ("Stratégie et architecture de reprise", "Recovery strategy and architecture"),
                   ("Procédures de reprise pas à pas", "Step-by-step recovery runbooks"),
                   ("Rapport de test et plan de correction", "Test report and remediation plan")],
  "faq": [
    (("Nos sauvegardes ne suffisent-elles pas ?", "Aren't our backups enough?"),
     ("Les sauvegardes sont nécessaires mais pas suffisantes. Il faut aussi savoir dans quel ordre restaurer, combien de temps cela prend réellement, et vérifier que les copies n'ont pas été compromises.",
      "Backups are necessary but not sufficient. You also need to know the restore order, how long it really takes, and that the copies have not been compromised.")),
    (("Être dans le nuage, est-ce une reprise après sinistre ?", "Isn't being in the cloud already disaster recovery?"),
     ("Pas automatiquement. Le fournisseur protège son infrastructure, mais vos données, configurations et accès restent votre responsabilité.",
      "Not automatically. The provider protects its infrastructure, but your data, configuration and access remain your responsibility.")),
  ],
  "related": ["what-we-do/expertise/cloud-resilience.html", "what-we-do/services/exercises.html"],
 },
 {
  "path": "what-we-do/expertise/cybersecurity.html",
  "short": ("Cybersécurité", "Cybersecurity"),
  "summary": ("Réduire les risques qui mènent aux incidents les plus coûteux, à commencer par les rançongiciels.",
              "Reduce the risks behind the most expensive incidents, starting with ransomware."),
  "title": ("Cybersécurité", "Cybersecurity"),
  "lede": ("Des bonnes pratiques concrètes, priorisées selon ce qui protège le mieux vos activités.",
           "Practical best practices, prioritized by what best protects your operations."),
  "intro": ("Nous ne vendons pas d'outils. Nous évaluons votre posture de sécurité par rapport à des référentiels reconnus, puis nous vous aidons à corriger ce qui compte le plus, dans le bon ordre.",
            "We don't sell tools. We assess your security posture against recognized frameworks, then help you fix what matters most, in the right order."),
  "cover": [
    (("Revue de la posture de sécurité", "Security posture review"),
     ("Évaluation fondée sur NIST CSF 2.0 et les CIS Controls, avec un plan priorisé.", "Assessment based on NIST CSF 2.0 and the CIS Controls, with a prioritized plan.")),
    (("Identités et accès", "Identity and access"),
     ("MFA, accès privilégiés et comptes de service, souvent la première porte d'entrée des attaquants.", "MFA, privileged access and service accounts, often the attacker's first way in.")),
    (("Préparation aux rançongiciels", "Ransomware readiness"),
     ("Prévention, détection, isolement et reprise, vérifiés ensemble.", "Prevention, detection, containment and recovery, checked together.")),
    (("Réponse aux incidents", "Incident response"),
     ("Plan de réponse, scénarios types et contacts d'urgence prêts à l'emploi.", "Response plan, playbooks and emergency contacts, ready to use.")),
    (("Gestion des vulnérabilités", "Vulnerability management"),
     ("Pratiques de correctifs et de durcissement adaptées à votre capacité réelle.", "Patching and hardening practices sized to your real capacity.")),
  ],
  "deliverables": [("Évaluation de maturité et registre des risques", "Maturity assessment and risk register"),
                   ("Feuille de route priorisée sur 12 mois", "Prioritized 12-month roadmap"),
                   ("Plan et scénarios de réponse aux incidents", "Incident response plan and playbooks"),
                   ("Politiques et normes de sécurité", "Security policies and standards")],
  "faq": [
    (("Vendez-vous des logiciels ou du matériel ?", "Do you sell software or hardware?"),
     ("Non. Nos recommandations sont indépendantes des fournisseurs. Nous vous aidons à tirer le meilleur de ce que vous avez déjà et à choisir si un nouvel outil est vraiment nécessaire.",
      "No. Our recommendations are vendor-neutral. We help you get the most from what you already have and decide whether a new tool is really needed.")),
    (("Faites-vous des tests d'intrusion ?", "Do you run penetration tests?"),
     ("Nous pouvons définir le périmètre, sélectionner un prestataire spécialisé et vous aider à interpréter et corriger les résultats.",
      "We can scope the test, help select a specialist provider, and help you interpret and fix the findings.")),
  ],
  "related": ["what-we-do/expertise/disaster-recovery.html", "what-we-do/services/assessments.html"],
 },
 {
  "path": "what-we-do/expertise/cloud-resilience.html",
  "short": ("Résilience infonuagique et des infrastructures", "Cloud and infrastructure resilience"),
  "summary": ("Éliminer les points de défaillance uniques dans le nuage, sur site et dans vos applications SaaS.",
              "Remove single points of failure in the cloud, on-premises and in your SaaS applications."),
  "title": ("Résilience infonuagique et des infrastructures", "Cloud and infrastructure resilience"),
  "lede": ("Des architectures qui tolèrent la panne d'un composant, d'une zone ou d'un fournisseur.",
           "Architectures that tolerate the failure of a component, a zone or a provider."),
  "intro": ("Les pannes majeures viennent souvent d'une dépendance que personne n'avait identifiée. Nous examinons votre architecture pour trouver ces points faibles et proposer des corrections proportionnées au risque.",
            "Major outages often come from a dependency nobody had identified. We review your architecture to find those weak points and propose fixes proportionate to the risk."),
  "cover": [
    (("Revue d'architecture", "Architecture review"),
     ("Redondance, zones et régions, réseau, DNS et identités dans AWS, Azure ou Google Cloud.", "Redundancy, zones and regions, networking, DNS and identity across AWS, Azure or Google Cloud.")),
    (("Responsabilité partagée", "Shared responsibility"),
     ("Clarifier ce que le fournisseur couvre et ce qui reste à votre charge.", "Clarify what the provider covers and what remains yours.")),
    (("Protection des données SaaS", "SaaS data protection"),
     ("Sauvegarde et reprise pour Microsoft 365, Google Workspace et vos applications métier.", "Backup and recovery for Microsoft 365, Google Workspace and business applications.")),
    (("Points de défaillance uniques", "Single points of failure"),
     ("Identifier les composants, personnes ou fournisseurs dont la perte arrêterait un service.", "Identify components, people or suppliers whose loss would stop a service.")),
    (("Supervision et alertes", "Monitoring and alerting"),
     ("Détecter la panne avant vos clients, avec des alertes qui arrivent aux bonnes personnes.", "Detect outages before your customers do, with alerts that reach the right people.")),
  ],
  "deliverables": [("Revue d'architecture et carte des risques", "Architecture review and risk map"),
                   ("Liste priorisée des points de défaillance uniques", "Prioritized list of single points of failure"),
                   ("Architecture cible et plan de transition", "Target architecture and transition plan")],
  "faq": [
    (("Travaillez-vous avec un fournisseur infonuagique en particulier ?", "Do you work with a specific cloud provider?"),
     ("Non. Nous travaillons avec AWS, Azure, Google Cloud et les environnements sur site ou hybrides.",
      "No. We work with AWS, Azure, Google Cloud and on-premises or hybrid environments.")),
  ],
  "related": ["what-we-do/expertise/disaster-recovery.html", "what-we-do/services/assessments.html"],
 },
]

SERVICES = [
 {
  "path": "what-we-do/services/assessments.html",
  "short": ("Évaluations", "Assessments"),
  "summary": ("Un portrait clair de votre résilience et une feuille de route priorisée.",
              "A clear picture of your resilience and a prioritized roadmap."),
  "title": ("Évaluations de résilience et de sécurité", "Resilience and security assessments"),
  "lede": ("Savoir où vous en êtes, ce qui compte le plus et par où commencer.",
           "Know where you stand, what matters most and where to start."),
  "intro": ("Un mandat à portée définie, généralement de quelques semaines selon la taille de l'organisation. Idéal comme point de départ, avant un audit ou après un incident.",
            "A fixed-scope engagement, usually a few weeks depending on the size of the organization. A good starting point, ahead of an audit or after an incident."),
  "cover": [
    (("Entretiens et collecte", "Interviews and discovery"), ("Direction, TI, opérations et fournisseurs clés.", "Leadership, IT, operations and key suppliers.")),
    (("Analyse", "Analysis"), ("Comparaison avec les référentiels pertinents et vos propres cibles.", "Comparison with relevant frameworks and your own targets.")),
    (("Restitution", "Readout"), ("Présentation des constats à la direction, en langage d'affaires.", "Findings presented to leadership, in business language.")),
  ],
  "deliverables": [("Rapport de constats et score de maturité", "Findings report and maturity score"),
                   ("Registre des risques", "Risk register"),
                   ("Feuille de route priorisée", "Prioritized roadmap"),
                   ("Présentation pour la direction", "Executive presentation")],
  "faq": [
    (("Faut-il beaucoup de temps de nos équipes ?", "Does it take a lot of our teams' time?"),
     ("Non. Nous regroupons les entretiens et réutilisons la documentation existante pour limiter l'effort de vos équipes.",
      "No. We group interviews and reuse existing documentation to keep the effort on your teams low.")),
  ],
  "related": ["what-we-do/expertise/cybersecurity.html", "what-we-do/methodology.html"],
 },
 {
  "path": "what-we-do/services/planning.html",
  "short": ("Planification et documentation", "Planning and documentation"),
  "summary": ("Plans, procédures et politiques que vos équipes peuvent réellement suivre.",
              "Plans, runbooks and policies your teams can actually follow."),
  "title": ("Planification et documentation", "Planning and documentation"),
  "lede": ("Des documents courts, à jour et utilisables sous pression.",
           "Documents that are short, current and usable under pressure."),
  "intro": ("Nous rédigeons avec vos équipes, pas à leur place. Le résultat reflète votre environnement réel et reste maintenable après notre départ.",
            "We write with your teams, not for them. The result reflects your real environment and stays maintainable after we leave."),
  "cover": [
    (("Plans de continuité et de reprise", "Continuity and recovery plans"), ("Structurés par service, avec rôles et critères de déclenchement.", "Structured by service, with roles and invocation criteria.")),
    (("Procédures techniques", "Technical runbooks"), ("Étapes précises et vérifiées pour restaurer chaque système.", "Precise, verified steps to restore each system.")),
    (("Politiques et normes", "Policies and standards"), ("Sécurité, sauvegarde, gestion des accès et des incidents.", "Security, backup, access and incident management.")),
  ],
  "deliverables": [("Plans de continuité et de reprise", "Continuity and recovery plans"),
                   ("Procédures de reprise", "Recovery runbooks"),
                   ("Politiques et normes", "Policies and standards"),
                   ("Processus de mise à jour", "Maintenance process")],
  "faq": [
    (("Dans quelle langue sont les documents ?", "What language are the documents in?"),
     ("En français, en anglais, ou dans les deux langues selon vos besoins.",
      "In French, English, or both, depending on your needs.")),
  ],
  "related": ["what-we-do/expertise/business-continuity.html", "what-we-do/services/exercises.html"],
 },
 {
  "path": "what-we-do/services/exercises.html",
  "short": ("Exercices et tests", "Exercises and testing"),
  "summary": ("Mettre vos plans à l'épreuve avant qu'un vrai incident ne le fasse.",
              "Put your plans to the test before a real incident does."),
  "title": ("Exercices et tests", "Exercises and testing"),
  "lede": ("Un plan non testé n'est qu'une hypothèse.",
           "An untested plan is only an assumption."),
  "intro": ("Nous concevons et animons des exercices réalistes, adaptés à votre secteur et à vos risques, puis nous transformons les constats en actions.",
            "We design and run realistic exercises, tailored to your sector and risks, then turn the findings into actions."),
  "cover": [
    (("Exercices sur table", "Tabletop exercises"), ("Scénarios guidés pour la direction et les équipes : rançongiciel, panne majeure, perte d'un fournisseur.", "Guided scenarios for leadership and teams: ransomware, major outage, supplier loss.")),
    (("Tests techniques", "Technical tests"), ("Restaurations et basculements réels, chronométrés et documentés.", "Real restores and failovers, timed and documented.")),
    (("Simulations de crise", "Crisis simulations"), ("Exercices plus complets impliquant communication et décisions en temps réel.", "Fuller exercises involving communication and real-time decisions.")),
  ],
  "deliverables": [("Scénario et dossier d'exercice", "Scenario and exercise pack"),
                   ("Rapport post-exercice", "After-action report"),
                   ("Plan de correction priorisé", "Prioritized remediation plan")],
  "faq": [
    (("Les exercices peuvent-ils se faire à distance ?", "Can exercises be run remotely?"),
     ("Oui. Les exercices sur table fonctionnent très bien en visioconférence, ce qui facilite la participation d'équipes réparties dans plusieurs pays.",
      "Yes. Tabletop exercises work very well over video, which makes it easy to include teams across several countries.")),
  ],
  "related": ["what-we-do/expertise/disaster-recovery.html", "what-we-do/services/planning.html"],
 },
 {
  "path": "what-we-do/services/advisory.html",
  "short": ("Accompagnement continu", "Ongoing advisory"),
  "summary": ("Un responsable résilience à temps partiel pour faire avancer la feuille de route.",
              "A part-time resilience lead to keep the roadmap moving."),
  "title": ("Accompagnement continu", "Ongoing advisory"),
  "lede": ("L'expertise d'un responsable résilience, sans embauche à temps plein.",
           "The expertise of a resilience lead, without a full-time hire."),
  "intro": ("Pour les organisations qui ont besoin d'un suivi régulier : mise en œuvre de la feuille de route, préparation réglementaire et rapports à la direction.",
            "For organizations that need regular follow-through: roadmap delivery, regulatory readiness and reporting to leadership."),
  "cover": [
    (("Pilotage de la feuille de route", "Roadmap delivery"), ("Suivi des actions, priorisation et coordination avec vos équipes et fournisseurs.", "Tracking actions, setting priorities and coordinating with your teams and suppliers.")),
    (("Préparation réglementaire", "Regulatory readiness"), ("Accompagnement face à DORA, NIS2, aux exigences FCA/PRA ou BSIF, et aux audits SOC 2.", "Support for DORA, NIS2, FCA/PRA or OSFI expectations, and SOC 2 audits.")),
    (("Rapports à la direction", "Leadership reporting"), ("Indicateurs clairs pour la direction et le conseil d'administration.", "Clear metrics for leadership and the board.")),
  ],
  "deliverables": [("Revue trimestrielle de la résilience", "Quarterly resilience review"),
                   ("Tableau de bord des risques et actions", "Risk and action dashboard"),
                   ("Soutien aux audits et questionnaires clients", "Support for audits and customer questionnaires")],
  "faq": [
    (("Comment se structure l'accompagnement ?", "How is ongoing advisory structured?"),
     ("Sur la base d'un nombre de jours par mois, ajusté selon la période : plus intense avant un audit, plus léger ensuite.",
      "As a number of days per month, adjusted over time: more before an audit, lighter afterwards.")),
  ],
  "related": ["what-we-do/regulations.html", "what-we-do/services/assessments.html"],
 },
]

METHOD = [
 (("Comprendre", "Understand"),
  ("Entretiens, inventaire et analyse d'impact pour établir ce qui compte vraiment et ce qu'une interruption coûterait.",
   "Interviews, inventory and impact analysis to establish what really matters and what an interruption would cost."),
  [("Analyse d'impact", "Impact analysis"), ("Cibles RTO et RPO", "RTO and RPO targets"), ("Registre des risques", "Risk register")]),
 (("Planifier", "Plan"),
  ("Une stratégie de reprise et de sécurité proportionnée au risque, traduite en plans et procédures utilisables.",
   "A recovery and security strategy proportionate to risk, turned into usable plans and procedures."),
  [("Stratégie de reprise", "Recovery strategy"), ("Plans et procédures", "Plans and runbooks"), ("Feuille de route", "Roadmap")]),
 (("Tester", "Test"),
  ("Exercices sur table et tests techniques pour mesurer l'écart réel avec vos cibles.",
   "Tabletop exercises and technical tests to measure the real gap to your targets."),
  [("Exercices", "Exercises"), ("Tests de restauration", "Restore tests"), ("Rapport post-exercice", "After-action report")]),
 (("Améliorer", "Improve"),
  ("Corrections priorisées, suivi et mise à jour des plans jusqu'au prochain cycle.",
   "Prioritized fixes, follow-up and plan updates until the next cycle."),
  [("Plan de correction", "Remediation plan"), ("Suivi des actions", "Action tracking"), ("Plans mis à jour", "Updated plans")]),
]

PRINCIPLES = [
 (("Indépendants des fournisseurs", "Vendor-neutral"), ("Nous ne revendons aucun produit. Nos recommandations servent votre intérêt.", "We resell no products. Our recommendations serve your interest.")),
 (("Prouvé par les tests", "Proven by testing"), ("Une capacité de reprise n'existe que si elle a été démontrée.", "A recovery capability only exists once it has been demonstrated.")),
 (("Proportionné", "Proportionate"), ("L'effort suit le risque. Pas de documentation pour le principe.", "Effort follows risk. No paperwork for its own sake.")),
 (("Bilingue", "Bilingual"), ("Nous travaillons en français et en anglais, avec des équipes de plusieurs pays.", "We work in French and English, with teams across several countries.")),
]

INDUSTRIES = [
 (("Services financiers", "Financial services"),
  ("Banques, assureurs, gestionnaires d'actifs et fintechs soumis à DORA, aux exigences FCA/PRA ou aux lignes directrices du BSIF.",
   "Banks, insurers, asset managers and fintechs subject to DORA, FCA/PRA rules or OSFI guidelines.")),
 (("Santé", "Healthcare"),
  ("Cliniques, laboratoires et fournisseurs de services de santé pour qui l'indisponibilité touche directement les patients.",
   "Clinics, labs and health service providers where downtime directly affects patients.")),
 (("Technologie et SaaS", "Technology and SaaS"),
  ("Éditeurs de logiciels qui doivent démontrer leur résilience à leurs clients et réussir leurs audits SOC 2.",
   "Software companies that must demonstrate resilience to customers and pass SOC 2 audits.")),
 (("Fabrication et logistique", "Manufacturing and logistics"),
  ("Organisations où une panne informatique arrête la production ou la livraison.",
   "Organizations where an IT outage stops production or delivery.")),
 (("Services professionnels", "Professional services"),
  ("Cabinets juridiques, comptables et de conseil qui protègent des données clients sensibles.",
   "Law, accounting and consulting firms protecting sensitive client data.")),
 (("Secteur public et OBNL", "Public sector and non-profits"),
  ("Organismes aux ressources limitées qui doivent maintenir des services essentiels à la population.",
   "Organizations with limited resources that must keep essential public services running.")),
]

HUB_FAQ = [
 (("En quoi êtes-vous différents d'un revendeur ou d'un intégrateur ?", "How are you different from a reseller or integrator?"),
  ("Nous ne vendons ni logiciels ni matériel. Nos revenus ne dépendent pas des produits recommandés, ce qui garde nos conseils indépendants.",
   "We sell no software or hardware. Our income does not depend on the products we recommend, which keeps our advice independent.")),
 (("Travaillez-vous avec les petites et moyennes organisations ?", "Do you work with small and mid-sized organizations?"),
  ("Oui. Nos mandats sont dimensionnés selon votre taille et votre niveau de risque, pas selon un modèle unique.",
   "Yes. Our engagements are sized to your organization and risk level, not a one-size-fits-all model.")),
 (("Travaillez-vous à distance ?", "Do you work remotely?"),
  ("Oui, en français et en anglais, avec des clients en Europe, au Royaume-Uni, au Canada et aux États-Unis.",
   "Yes, in French and English, with clients in Europe, the UK, Canada and the United States.")),
 (("Fournissez-vous des avis juridiques sur la conformité ?", "Do you provide legal advice on compliance?"),
  ("Non. Nous fournissons des conseils opérationnels et techniques et travaillons volontiers avec vos conseillers juridiques.",
   "No. We provide operational and technical advice and are happy to work alongside your legal advisers.")),
 (("Par où commencer ?", "Where should we start?"),
  ("Le plus souvent par une évaluation, qui établit vos priorités et une feuille de route. Un premier échange de 30 minutes permet de voir si c'est le bon point de départ.",
   "Usually with an assessment, which sets your priorities and a roadmap. A 30-minute intro call helps confirm whether that is the right starting point.")),
]
