# Page content for the FZ Consultation site. Every string is a (fr, en) pair.

EXPERTISE = [
 {
  "path": "what-we-do/expertise/business-continuity.html",
  "short": ("Continuité des activités", "Business continuity"),
  "summary": ("Garder les services essentiels en marche quand les personnes, les locaux ou les fournisseurs font défaut.",
              "Keep essential services running when people, sites or suppliers are unavailable."),
  "title": ("Continuité des activités", "Business continuity"),
  "lede": ("Savoir ce qui doit continuer, dans quel ordre et avec qui, avant que la crise ne commence.",
           "Know what must keep going, in what order and with whom, before the crisis starts."),
  "intro": ("Un plan de continuité utile ne se limite pas à l'informatique. Il couvre les personnes, les locaux, les fournisseurs et la communication. Nous partons de vos services essentiels et remontons jusqu'aux dépendances qui peuvent les interrompre.",
            "A useful continuity plan is not only about IT. It covers people, sites, suppliers and communication. We start from your essential services and work back to the dependencies that can interrupt them."),
  "cover": [
    (("Analyse d'impact sur les activités", "Business impact analysis"),
     ("Nous quantifions l'effet d'une interruption dans le temps, heure par heure plutôt que par une estimation globale. Cela permet de fixer des délais de reprise acceptables par service, plutôt qu'un objectif unique pour toute l'organisation.", "We quantify how an interruption hurts over time, hour by hour rather than as a single blanket estimate. That makes it possible to set acceptable recovery times per service, rather than one target for the whole organization.")),
    (("Cartographie des dépendances", "Dependency mapping"),
     ("Nous relions chaque service essentiel aux équipes, systèmes, sites et fournisseurs dont il dépend réellement, pas seulement à ce que l'organigramme technique suggère. Cette carte sert ensuite de base à tous vos plans de continuité et de reprise.", "We link each essential service to the teams, systems, sites and suppliers it actually depends on, not just what the technical org chart suggests. This map then becomes the foundation for every continuity and recovery plan you build.")),
    (("Plans de continuité", "Continuity plans"),
     ("Nous rédigeons des plans courts et actionnables, pensés pour être suivis pendant un incident plutôt que rangés dans un tiroir. Ils s'alignent sur ISO 22301 lorsque c'est pertinent pour votre organisation ou vos clients.", "We write short, actionable plans, meant to be followed during an incident rather than filed away. They align with ISO 22301 where that matters to your organization or your clients.")),
    (("Gestion de crise et communication", "Crisis management and communication"),
     ("Nous définissons les rôles et la chaîne de décision de votre cellule de crise, pour que chacun sache qui décide quoi. Des messages sont préparés à l'avance pour les employés, les clients et les régulateurs, afin de gagner un temps précieux le jour où ils sont nécessaires.", "We define the roles and decision chain of your crisis team, so everyone knows who decides what. Messages for staff, clients and regulators are prepared in advance, to save precious time on the day they are actually needed.")),
    (("Fournisseurs critiques", "Critical suppliers"),
     ("Nous évaluons la résilience de vos fournisseurs clés, au-delà de ce que promettent leurs contrats. Quand un fournisseur présente un risque trop élevé, nous vous aidons à préparer des solutions de rechange réalistes.", "We assess the resilience of your key suppliers, beyond what their contracts promise. Where a supplier carries too much risk, we help you prepare realistic alternatives.")),
  ],
  "deliverables": [("Rapport d'analyse d'impact", "Business impact analysis report"),
                   ("Registre des services essentiels et dépendances", "Register of essential services and dependencies"),
                   ("Plan de continuité et plan de gestion de crise", "Continuity plan and crisis management plan"),
                   ("Modèles de communication de crise", "Crisis communication templates")],
  "faq": [
    (("Quelle est la différence entre continuité des activités et reprise après sinistre ?", "What is the difference between business continuity and disaster recovery?"),
     ("La continuité des activités vise à maintenir l'organisation en fonctionnement dans son ensemble. La reprise après sinistre en est une partie : elle porte sur le rétablissement des systèmes et des données.",
      "Business continuity is about keeping the whole organization operating. Disaster recovery is one part of it, focused on restoring systems and data.")),
    (("À quelle fréquence faut-il mettre à jour un plan ?", "How often should a plan be updated?"),
     ("Au minimum une fois par an, et après tout changement important : nouveau système, nouveau fournisseur, réorganisation ou incident réel.",
      "At least once a year, and after any significant change: a new system, a new supplier, a reorganization or a real incident.")),
  ],
  "related": ["what-we-do/expertise/disaster-recovery.html", "what-we-do/services/exercises.html"],
 },
 {
  "path": "what-we-do/expertise/disaster-recovery.html",
  "short": ("Reprise après sinistre", "Disaster recovery"),
  "summary": ("Restaurer systèmes et données dans les délais que l'entreprise peut se permettre.",
              "Restore systems and data within the time the business can afford."),
  "title": ("Reprise après sinistre", "Disaster recovery"),
  "lede": ("Une reprise qui fonctionne le jour où vous en avez besoin, pas seulement sur papier.",
           "Recovery that works on the day you need it, not just on paper."),
  "intro": ("Nous fixons avec vous des cibles RTO et RPO réalistes, puis nous concevons, documentons et vérifions la façon de les atteindre, que vos systèmes soient sur site, dans le nuage ou hybrides.",
            "We work with you to set realistic RTO and RPO targets, then design, document and verify how to meet them, whether your systems are on-premises, in the cloud or hybrid."),
  "cover": [
    (("Cibles RTO et RPO", "RTO and RPO targets"),
     ("Nous fixons des objectifs par service, fondés sur l'impact réel d'une interruption pour votre organisation, et non sur des moyennes de secteur qui ne correspondent à personne en particulier. Ces cibles servent ensuite de fil conducteur à toute la stratégie de reprise.", "We set targets per service, based on the real impact an interruption would have on your organization, not on industry averages that fit no one in particular. These targets then guide the whole recovery strategy.")),
    (("Architecture de reprise", "Recovery architecture"),
     ("Nous révisons ou concevons vos sites secondaires, vos mécanismes de réplication et votre reprise infonuagique. L'objectif est une architecture qui tient ses promesses le jour où elle est sollicitée, pas seulement sur un schéma.", "We review or design your secondary sites, replication mechanisms and cloud recovery setup. The goal is an architecture that delivers on its promises the day it is actually called on, not just on a diagram.")),
    (("Stratégie de sauvegarde", "Backup strategy"),
     ("Nous concevons une stratégie de sauvegarde avec des copies isolées et immuables, résistantes aux rançongiciels qui ciblent désormais les sauvegardes elles-mêmes. Chaque copie est accompagnée d'une restauration vérifiée, pas seulement d'un journal qui indique qu'elle a réussi.", "We design a backup strategy with isolated, immutable copies that resist the ransomware now specifically targeting backups. Every copy comes with a verified restore, not just a log that says it succeeded.")),
    (("Procédures de reprise", "Recovery runbooks"),
     ("Nous documentons des étapes précises, ordonnées selon les dépendances techniques réelles entre vos systèmes. Elles sont écrites pour être suivies par une équipe sous pression, à trois heures du matin, pas pour impressionner un auditeur.", "We document precise steps, ordered by the real technical dependencies between your systems. They are written to be followed by a team under pressure, at three in the morning, not to impress an auditor.")),
    (("Tests de reprise", "Recovery testing"),
     ("Nous exécutons des restaurations et des basculements réels, chronométrés, pour mesurer l'écart entre vos cibles et ce qui se passe vraiment. Chaque test se termine par une liste de corrections concrètes, pas seulement par un constat.", "We run real, timed restores and failovers, to measure the gap between your targets and what actually happens. Every test ends with a list of concrete fixes, not just a finding.")),
  ],
  "deliverables": [("Cibles RTO et RPO validées par la direction", "RTO and RPO targets signed off by leadership"),
                   ("Stratégie et architecture de reprise", "Recovery strategy and architecture"),
                   ("Procédures de reprise pas à pas", "Step-by-step recovery runbooks"),
                   ("Rapport de test et plan de correction", "Test report and remediation plan")],
  "faq": [
    (("Nos sauvegardes ne suffisent-elles pas ?", "Aren't our backups enough?"),
     ("Les sauvegardes sont nécessaires mais pas suffisantes. Il faut aussi savoir dans quel ordre restaurer, combien de temps cela prend réellement, et vérifier que les copies n'ont pas été compromises.",
      "Backups are necessary but not sufficient. You also need to know the restore order, how long it really takes, and that the copies have not been compromised.")),
    (("Être dans le nuage, est-ce une reprise après sinistre ?", "Isn't being in the cloud already disaster recovery?"),
     ("Pas automatiquement. Le fournisseur protège son infrastructure, mais vos données, configurations et accès restent votre responsabilité.",
      "Not automatically. The provider protects its infrastructure, but your data, configuration and access remain your responsibility.")),
  ],
  "related": ["what-we-do/expertise/cloud-resilience.html", "what-we-do/services/exercises.html"],
 },
 {
  "path": "what-we-do/expertise/cybersecurity.html",
  "short": ("Cybersécurité", "Cybersecurity"),
  "summary": ("Réduire les risques qui mènent aux incidents les plus coûteux, à commencer par les rançongiciels.",
              "Reduce the risks behind the most expensive incidents, starting with ransomware."),
  "title": ("Cybersécurité", "Cybersecurity"),
  "lede": ("Des bonnes pratiques concrètes, priorisées selon ce qui protège le mieux vos activités.",
           "Practical best practices, prioritized by what best protects your operations."),
  "intro": ("Nous ne vendons pas d'outils. Nous évaluons votre posture de sécurité par rapport à des référentiels reconnus, puis nous vous aidons à corriger ce qui compte le plus, dans le bon ordre.",
            "We don't sell tools. We assess your security posture against recognized frameworks, then help you fix what matters most, in the right order."),
  "cover": [
    (("Revue de la posture de sécurité", "Security posture review"),
     ("Nous évaluons votre posture de sécurité par rapport à NIST CSF 2.0 et aux CIS Controls, deux référentiels reconnus et indépendants des fournisseurs. Le résultat est un plan priorisé selon ce qui réduit le plus le risque, pas selon ce qui est le plus visible.", "We assess your security posture against NIST CSF 2.0 and the CIS Controls, two recognized, vendor-neutral frameworks. The result is a plan prioritized by what reduces risk the most, not by what is most visible.")),
    (("Identités et accès", "Identity and access"),
     ("Nous examinons la MFA, les accès privilégiés et les comptes de service, qui restent la première porte d'entrée des attaquants dans la grande majorité des incidents. Ces vérifications simples produisent souvent le meilleur rapport entre effort et réduction du risque.", "We review MFA, privileged access and service accounts, still the attacker's first way in for the vast majority of incidents. These simple checks often deliver the best return for the effort involved.")),
    (("Préparation aux rançongiciels", "Ransomware readiness"),
     ("Nous vérifions ensemble la prévention, la détection, l'isolement et la reprise face aux rançongiciels, car une chaîne n'est solide que si chaque maillon l'est. Un excellent outil de détection ne sert à rien si personne ne sait ensuite isoler et restaurer.", "We check ransomware prevention, detection, containment and recovery together, because a chain is only as strong as its weakest link. An excellent detection tool is worthless if no one then knows how to contain and restore.")),
    (("Réponse aux incidents", "Incident response"),
     ("Nous rédigeons un plan de réponse aux incidents avec des scénarios types pour les cas les plus probables, et une liste de contacts d'urgence prête à l'emploi. Le but est de retirer les décisions difficiles du moment de crise, en les prenant à froid.", "We write an incident response plan with playbooks for your most likely scenarios, and a ready-to-use list of emergency contacts. The aim is to take the hard decisions out of the crisis moment, by making them ahead of time.")),
    (("Gestion des vulnérabilités", "Vulnerability management"),
     ("Nous adaptons les pratiques de correctifs et de durcissement à votre capacité réelle, plutôt que de recommander un programme que personne n'a les moyens de suivre. L'objectif est un rythme soutenable qui se maintient après notre départ.", "We size patching and hardening practices to your real capacity, rather than recommending a program no one can actually sustain. The goal is a pace that holds up after we leave.")),
  ],
  "deliverables": [("Évaluation de maturité et registre des risques", "Maturity assessment and risk register"),
                   ("Feuille de route priorisée sur 12 mois", "Prioritized 12-month roadmap"),
                   ("Plan et scénarios de réponse aux incidents", "Incident response plan and playbooks"),
                   ("Politiques et normes de sécurité", "Security policies and standards")],
  "faq": [
    (("Vendez-vous des logiciels ou du matériel ?", "Do you sell software or hardware?"),
     ("Non. Nos recommandations sont indépendantes des fournisseurs. Nous vous aidons à tirer le meilleur de ce que vous avez déjà et à choisir si un nouvel outil est vraiment nécessaire.",
      "No. Our recommendations are vendor-neutral. We help you get the most from what you already have and decide whether a new tool is really needed.")),
    (("Faites-vous des tests d'intrusion ?", "Do you run penetration tests?"),
     ("Nous pouvons définir le périmètre, sélectionner un prestataire spécialisé et vous aider à interpréter et corriger les résultats.",
      "We can scope the test, help select a specialist provider, and help you interpret and fix the findings.")),
  ],
  "related": ["what-we-do/expertise/disaster-recovery.html", "what-we-do/services/assessments.html"],
 },
 {
  "path": "what-we-do/expertise/cloud-resilience.html",
  "short": ("Résilience infonuagique et des infrastructures", "Cloud and infrastructure resilience"),
  "summary": ("Éliminer les points de défaillance uniques dans le nuage, sur site et dans vos applications SaaS.",
              "Remove single points of failure in the cloud, on-premises and in your SaaS applications."),
  "title": ("Résilience infonuagique et des infrastructures", "Cloud and infrastructure resilience"),
  "lede": ("Des architectures qui tolèrent la panne d'un composant, d'une zone ou d'un fournisseur.",
           "Architectures that tolerate the failure of a component, a zone or a provider."),
  "intro": ("Les pannes majeures viennent souvent d'une dépendance que personne n'avait identifiée. Nous examinons votre architecture pour trouver ces points faibles et proposer des corrections proportionnées au risque.",
            "Major outages often come from a dependency nobody had identified. We review your architecture to find those weak points and propose fixes proportionate to the risk."),
  "cover": [
    (("Revue d'architecture", "Architecture review"),
     ("Nous examinons la redondance, les zones et régions, le réseau, le DNS et la gestion des identités dans AWS, Azure ou Google Cloud. Ces éléments sont souvent la cause réelle d'une panne que l'on croyait limitée à une seule application.", "We review redundancy, zones and regions, networking, DNS and identity management across AWS, Azure or Google Cloud. These are often the real cause of an outage that looked, at first, like it was limited to a single application.")),
    (("Responsabilité partagée", "Shared responsibility"),
     ("Nous clarifions ce que votre fournisseur infonuagique couvre réellement et ce qui reste de votre responsabilité, un point souvent mal compris entre les équipes techniques et la direction. Cette clarté évite les mauvaises surprises au pire moment.", "We clarify what your cloud provider actually covers and what remains your responsibility, a point often misunderstood between technical teams and leadership. That clarity avoids unpleasant surprises at the worst possible time.")),
    (("Protection des données SaaS", "SaaS data protection"),
     ("Nous mettons en place la sauvegarde et la reprise de Microsoft 365, Google Workspace et de vos applications métier critiques. Ces plateformes protègent leur propre infrastructure, mais rarement vos données contre une suppression accidentelle ou malveillante.", "We set up backup and recovery for Microsoft 365, Google Workspace and your critical business applications. These platforms protect their own infrastructure, but rarely your data against accidental or malicious deletion.")),
    (("Points de défaillance uniques", "Single points of failure"),
     ("Nous identifions les composants, les personnes ou les fournisseurs dont la seule perte suffirait à arrêter un service entier. Ces points de défaillance uniques sont souvent invisibles jusqu'au jour où ils causent la panne.", "We identify the components, people or suppliers whose loss alone would be enough to stop an entire service. These single points of failure are often invisible until the day they cause the outage.")),
    (("Supervision et alertes", "Monitoring and alerting"),
     ("Nous mettons en place une supervision qui détecte la panne avant vos clients, avec des alertes qui arrivent réellement aux bonnes personnes, à toute heure. Une alerte que personne ne voit n'a pas plus de valeur qu'une absence de supervision.", "We set up monitoring that detects an outage before your customers do, with alerts that actually reach the right people, at any hour. An alert no one sees is worth no more than having no monitoring at all.")),
  ],
  "deliverables": [("Revue d'architecture et carte des risques", "Architecture review and risk map"),
                   ("Liste priorisée des points de défaillance uniques", "Prioritized list of single points of failure"),
                   ("Architecture cible et plan de transition", "Target architecture and transition plan")],
  "faq": [
    (("Travaillez-vous avec un fournisseur infonuagique en particulier ?", "Do you work with a specific cloud provider?"),
     ("Non. Nous travaillons avec AWS, Azure, Google Cloud et les environnements sur site ou hybrides.",
      "No. We work with AWS, Azure, Google Cloud and on-premises or hybrid environments.")),
  ],
  "related": ["what-we-do/expertise/disaster-recovery.html", "what-we-do/services/assessments.html"],
 },
]

SERVICES = [
 {
  "path": "what-we-do/services/assessments.html",
  "short": ("Évaluations", "Assessments"),
  "summary": ("Un portrait clair de votre résilience et une feuille de route priorisée.",
              "A clear picture of your resilience and a prioritized roadmap."),
  "title": ("Évaluations de résilience et de sécurité", "Resilience and security assessments"),
  "lede": ("Savoir où vous en êtes, ce qui compte le plus et par où commencer.",
           "Know where you stand, what matters most and where to start."),
  "intro": ("Un mandat à portée définie, généralement de quelques semaines selon la taille de l'organisation. Idéal comme point de départ, avant un audit ou après un incident.",
            "A fixed-scope engagement, usually a few weeks depending on the size of the organization. A good starting point, ahead of an audit or after an incident."),
  "cover": [
    (("Entretiens et collecte", "Interviews and discovery"), ("Nous menons des entretiens groupés avec la direction, les équipes TI, les opérations et vos fournisseurs clés. Ce format limite le temps demandé à chaque personne tout en couvrant l'ensemble de l'organisation.", "We run grouped interviews with leadership, IT teams, operations and your key suppliers. This format keeps the time asked of each person low while still covering the whole organization.")),
    (("Analyse", "Analysis"), ("Nous comparons vos pratiques aux référentiels pertinents pour votre secteur, ainsi qu'à vos propres cibles quand elles existent déjà. L'écart entre les deux devient la base de la feuille de route qui suit.", "We compare your practices against the frameworks relevant to your sector, and against your own targets where they already exist. The gap between the two becomes the basis for the roadmap that follows.")),
    (("Restitution", "Readout"), ("Nous présentons les constats à la direction en langage d'affaires, traduits en risques et en décisions plutôt qu'en jargon technique. C'est souvent ce qui permet enfin d'obtenir le budget ou le mandat nécessaire pour agir.", "We present the findings to leadership in business language, translated into risks and decisions rather than technical jargon. This is often what finally unlocks the budget or mandate needed to act.")),
  ],
  "deliverables": [("Rapport de constats et score de maturité", "Findings report and maturity score"),
                   ("Registre des risques", "Risk register"),
                   ("Feuille de route priorisée", "Prioritized roadmap"),
                   ("Présentation pour la direction", "Executive presentation")],
  "faq": [
    (("Faut-il beaucoup de temps de nos équipes ?", "Does it take a lot of our teams' time?"),
     ("Non. Nous regroupons les entretiens et réutilisons la documentation existante pour limiter l'effort de vos équipes.",
      "No. We group interviews and reuse existing documentation to keep the effort on your teams low.")),
  ],
  "related": ["what-we-do/expertise/cybersecurity.html", "what-we-do/methodology.html"],
 },
 {
  "path": "what-we-do/services/planning.html",
  "short": ("Planification et documentation", "Planning and documentation"),
  "summary": ("Plans, procédures et politiques que vos équipes peuvent réellement suivre.",
              "Plans, runbooks and policies your teams can actually follow."),
  "title": ("Planification et documentation", "Planning and documentation"),
  "lede": ("Des documents courts, à jour et utilisables sous pression.",
           "Documents that are short, current and usable under pressure."),
  "intro": ("Nous rédigeons avec vos équipes, pas à leur place. Le résultat reflète votre environnement réel et reste maintenable après notre départ.",
            "We write with your teams, not for them. The result reflects your real environment and stays maintainable after we leave."),
  "cover": [
    (("Plans de continuité et de reprise", "Continuity and recovery plans"), ("Nos plans de continuité et de reprise sont structurés par service, avec des rôles clairs et des critères précis pour savoir quand les déclencher. Cette structure évite l'hésitation qui coûte le plus de temps au début d'un incident.", "Our continuity and recovery plans are structured by service, with clear roles and precise criteria for when to invoke them. This structure avoids the hesitation that costs the most time in the first minutes of an incident.")),
    (("Procédures techniques", "Technical runbooks"), ("Nous rédigeons des étapes précises et vérifiées pour restaurer chaque système, testées avec les personnes qui les suivront réellement. Une procédure qui n'a jamais été essayée est une hypothèse, pas un plan.", "We write precise, verified steps to restore each system, tested with the people who will actually follow them. A procedure that has never been tried is an assumption, not a plan.")),
    (("Politiques et normes", "Policies and standards"), ("Nous rédigeons ou révisons vos politiques de sécurité, de sauvegarde, de gestion des accès et de gestion des incidents. Elles restent courtes et concrètes, pour être réellement lues et suivies plutôt que classées sans être ouvertes.", "We write or review your security, backup, access and incident management policies. They stay short and concrete, so they are actually read and followed rather than filed away unopened.")),
  ],
  "deliverables": [("Plans de continuité et de reprise", "Continuity and recovery plans"),
                   ("Procédures de reprise", "Recovery runbooks"),
                   ("Politiques et normes", "Policies and standards"),
                   ("Processus de mise à jour", "Maintenance process")],
  "faq": [
    (("Dans quelle langue sont les documents ?", "What language are the documents in?"),
     ("En français, en anglais, ou dans les deux langues selon vos besoins.",
      "In French, English, or both, depending on your needs.")),
  ],
  "related": ["what-we-do/expertise/business-continuity.html", "what-we-do/services/exercises.html"],
 },
 {
  "path": "what-we-do/services/exercises.html",
  "short": ("Exercices et tests", "Exercises and testing"),
  "summary": ("Mettre vos plans à l'épreuve avant qu'un vrai incident ne le fasse.",
              "Put your plans to the test before a real incident does."),
  "title": ("Exercices et tests", "Exercises and testing"),
  "lede": ("Un plan non testé n'est qu'une hypothèse.",
           "An untested plan is only an assumption."),
  "intro": ("Nous concevons et animons des exercices réalistes, adaptés à votre secteur et à vos risques, puis nous transformons les constats en actions.",
            "We design and run realistic exercises, tailored to your sector and risks, then turn the findings into actions."),
  "cover": [
    (("Exercices sur table", "Tabletop exercises"), ("Nous animons des scénarios guidés pour la direction et les équipes, comme un rançongiciel, une panne majeure ou la perte d'un fournisseur critique. Chaque exercice révèle des angles morts qu'aucun document n'aurait mis en évidence seul.", "We run guided scenarios for leadership and teams, such as a ransomware attack, a major outage or the loss of a critical supplier. Each exercise reveals blind spots that no document could have surfaced on its own.")),
    (("Tests techniques", "Technical tests"), ("Nous exécutons des restaurations et des basculements réels, chronométrés et documentés, plutôt que de nous fier à ce que la documentation affirme. Le résultat donne un RTO mesuré, pas seulement estimé.", "We run real restores and failovers, timed and documented, rather than relying on what the documentation claims. The result is a measured RTO, not just an estimated one.")),
    (("Simulations de crise", "Crisis simulations"), ("Nous concevons des simulations de crise plus complètes, qui combinent décisions techniques, communication externe et pression du temps réel. Elles préparent la direction à décider dans l'incertitude, pas seulement les équipes techniques à restaurer des systèmes.", "We design fuller crisis simulations that combine technical decisions, external communication and real-time pressure. They prepare leadership to decide under uncertainty, not just technical teams to restore systems.")),
  ],
  "deliverables": [("Scénario et dossier d'exercice", "Scenario and exercise pack"),
                   ("Rapport post-exercice", "After-action report"),
                   ("Plan de correction priorisé", "Prioritized remediation plan")],
  "faq": [
    (("Les exercices peuvent-ils se faire à distance ?", "Can exercises be run remotely?"),
     ("Oui. Les exercices sur table fonctionnent très bien en visioconférence, ce qui facilite la participation d'équipes réparties dans plusieurs pays.",
      "Yes. Tabletop exercises work very well over video, which makes it easy to include teams across several countries.")),
  ],
  "related": ["what-we-do/expertise/disaster-recovery.html", "what-we-do/services/planning.html"],
 },
 {
  "path": "what-we-do/services/advisory.html",
  "short": ("Accompagnement continu", "Ongoing advisory"),
  "summary": ("Un responsable résilience à temps partiel pour faire avancer la feuille de route.",
              "A part-time resilience lead to keep the roadmap moving."),
  "title": ("Accompagnement continu", "Ongoing advisory"),
  "lede": ("L'expertise d'un responsable résilience, sans embauche à temps plein.",
           "The expertise of a resilience lead, without a full-time hire."),
  "intro": ("Pour les organisations qui ont besoin d'un suivi régulier : mise en œuvre de la feuille de route, préparation réglementaire et rapports à la direction.",
            "For organizations that need regular follow-through: roadmap delivery, regulatory readiness and reporting to leadership."),
  "cover": [
    (("Pilotage de la feuille de route", "Roadmap delivery"), ("Nous assurons le suivi des actions de votre feuille de route, la priorisation continue selon l'évolution des risques, et la coordination avec vos équipes internes et vos fournisseurs. C'est souvent ce suivi régulier, plus que le plan initial, qui détermine si une feuille de route aboutit vraiment.", "We track the actions on your roadmap, keep priorities current as risks evolve, and coordinate with your internal teams and suppliers. This regular follow-through, more than the initial plan, is usually what determines whether a roadmap actually gets delivered.")),
    (("Préparation réglementaire", "Regulatory readiness"), ("Nous vous accompagnons face à DORA, NIS2, aux exigences FCA/PRA ou du BSIF, et aux audits SOC 2, selon les marchés où vous opérez. Cet accompagnement inclut la préparation des preuves, pas seulement l'interprétation du texte réglementaire.", "We support you through DORA, NIS2, FCA/PRA or OSFI expectations, and SOC 2 audits, depending on the markets you operate in. This support includes preparing the evidence itself, not just interpreting the regulatory text.")),
    (("Rapports à la direction", "Leadership reporting"), ("Nous produisons des indicateurs clairs pour la direction et le conseil d'administration, qui montrent l'évolution réelle du risque plutôt qu'une liste de tâches accomplies. Ces rapports servent aussi de trace en cas de question d'un régulateur ou d'un client.", "We produce clear metrics for leadership and the board, showing how risk is actually evolving rather than a list of completed tasks. These reports also serve as a record if a regulator or client ever asks.")),
  ],
  "deliverables": [("Revue trimestrielle de la résilience", "Quarterly resilience review"),
                   ("Tableau de bord des risques et actions", "Risk and action dashboard"),
                   ("Soutien aux audits et questionnaires clients", "Support for audits and customer questionnaires")],
  "faq": [
    (("Comment se structure l'accompagnement ?", "How is ongoing advisory structured?"),
     ("Sur la base d'un nombre de jours par mois, ajusté selon la période : plus intense avant un audit, plus léger ensuite.",
      "As a number of days per month, adjusted over time: more before an audit, lighter afterwards.")),
  ],
  "related": ["what-we-do/regulations.html", "what-we-do/services/assessments.html"],
 },
]

METHOD = [
 (("Comprendre", "Understand"),
  ("Entretiens, inventaire et analyse d'impact pour établir ce qui compte vraiment et ce qu'une interruption coûterait.",
   "Interviews, inventory and impact analysis to establish what really matters and what an interruption would cost."),
  [("Analyse d'impact", "Impact analysis"), ("Cibles RTO et RPO", "RTO and RPO targets"), ("Registre des risques", "Risk register")]),
 (("Planifier", "Plan"),
  ("Une stratégie de reprise et de sécurité proportionnée au risque, traduite en plans et procédures utilisables.",
   "A recovery and security strategy proportionate to risk, turned into usable plans and procedures."),
  [("Stratégie de reprise", "Recovery strategy"), ("Plans et procédures", "Plans and runbooks"), ("Feuille de route", "Roadmap")]),
 (("Tester", "Test"),
  ("Exercices sur table et tests techniques pour mesurer l'écart réel avec vos cibles.",
   "Tabletop exercises and technical tests to measure the real gap to your targets."),
  [("Exercices", "Exercises"), ("Tests de restauration", "Restore tests"), ("Rapport post-exercice", "After-action report")]),
 (("Améliorer", "Improve"),
  ("Corrections priorisées, suivi et mise à jour des plans jusqu'au prochain cycle.",
   "Prioritized fixes, follow-up and plan updates until the next cycle."),
  [("Plan de correction", "Remediation plan"), ("Suivi des actions", "Action tracking"), ("Plans mis à jour", "Updated plans")]),
]

PRINCIPLES = [
 (("Indépendants des fournisseurs", "Vendor-neutral"), ("Nous ne revendons aucun produit. Nos recommandations servent votre intérêt.", "We resell no products. Our recommendations serve your interest.")),
 (("Prouvé par les tests", "Proven by testing"), ("Une capacité de reprise n'existe que si elle a été démontrée.", "A recovery capability only exists once it has been demonstrated.")),
 (("Proportionné", "Proportionate"), ("L'effort suit le risque. Pas de documentation pour le principe.", "Effort follows risk. No paperwork for its own sake.")),
 (("Bilingue", "Bilingual"), ("Nous travaillons en français et en anglais, avec des équipes de plusieurs pays.", "We work in French and English, with teams across several countries.")),
]

INDUSTRIES = [
 (("Services financiers", "Financial services"),
  ("Banques, assureurs, gestionnaires d'actifs et fintechs soumis à DORA, aux exigences FCA/PRA ou aux lignes directrices du BSIF.",
   "Banks, insurers, asset managers and fintechs subject to DORA, FCA/PRA rules or OSFI guidelines.")),
 (("Santé", "Healthcare"),
  ("Cliniques, laboratoires et fournisseurs de services de santé pour qui l'indisponibilité touche directement les patients.",
   "Clinics, labs and health service providers where downtime directly affects patients.")),
 (("Technologie et SaaS", "Technology and SaaS"),
  ("Éditeurs de logiciels qui doivent démontrer leur résilience à leurs clients et réussir leurs audits SOC 2.",
   "Software companies that must demonstrate resilience to customers and pass SOC 2 audits.")),
 (("Fabrication et logistique", "Manufacturing and logistics"),
  ("Organisations où une panne informatique arrête la production ou la livraison.",
   "Organizations where an IT outage stops production or delivery.")),
 (("Services professionnels", "Professional services"),
  ("Cabinets juridiques, comptables et de conseil qui protègent des données clients sensibles.",
   "Law, accounting and consulting firms protecting sensitive client data.")),
 (("Secteur public et OBNL", "Public sector and non-profits"),
  ("Organismes aux ressources limitées qui doivent maintenir des services essentiels à la population.",
   "Organizations with limited resources that must keep essential public services running.")),
]

HUB_FAQ = [
 (("En quoi êtes-vous différents d'un revendeur ou d'un intégrateur ?", "How are you different from a reseller or integrator?"),
  ("Nous ne vendons ni logiciels ni matériel. Nos revenus ne dépendent pas des produits recommandés, ce qui garde nos conseils indépendants.",
   "We sell no software or hardware. Our income does not depend on the products we recommend, which keeps our advice independent.")),
 (("Travaillez-vous avec les petites et moyennes organisations ?", "Do you work with small and mid-sized organizations?"),
  ("Oui. Nos mandats sont dimensionnés selon votre taille et votre niveau de risque, pas selon un modèle unique.",
   "Yes. Our engagements are sized to your organization and risk level, not a one-size-fits-all model.")),
 (("Travaillez-vous à distance ?", "Do you work remotely?"),
  ("Oui, en français et en anglais, avec des clients en Europe, au Royaume-Uni, au Canada et aux États-Unis.",
   "Yes, in French and English, with clients in Europe, the UK, Canada and the United States.")),
 (("Fournissez-vous des avis juridiques sur la conformité ?", "Do you provide legal advice on compliance?"),
  ("Non. Nous fournissons des conseils opérationnels et techniques et travaillons volontiers avec vos conseillers juridiques.",
   "No. We provide operational and technical advice and are happy to work alongside your legal advisers.")),
 (("Par où commencer ?", "Where should we start?"),
  ("Le plus souvent par une évaluation, qui établit vos priorités et une feuille de route. Un premier échange de 30 minutes permet de voir si c'est le bon point de départ.",
   "Usually with an assessment, which sets your priorities and a roadmap. A 30-minute intro call helps confirm whether that is the right starting point.")),
]
