# Cost-of-downtime page content. Every figure below is attributed to a public source
# listed in SOURCES; figures are industry estimates that vary by methodology, not guarantees.

BENCH_GENERAL = [
 (("91 % des moyennes et grandes entreprises", "91% of mid-size and large enterprises"),
  ("estiment le coût d'une heure de panne à plus de 300 000 $ US.", "estimate the cost of one hour of downtime at more than US$300,000."), 0),
 (("41 % des grandes entreprises", "41% of large enterprises"),
  ("estiment ce coût entre 1 M$ et plus de 5 M$ US par heure.", "put that cost between $1M and over $5M US per hour."), 0),
 (("Référence historique la plus citée", "Most-cited historical benchmark"),
  ("5 600 $ US par minute, soit environ 336 000 $ US par heure (Gartner, 2014).", "$5,600 US per minute, about $336,000 US per hour (Gartner, 2014)."), 1),
]

BY_INDUSTRY = [
 {"industry": ("Services financiers", "Financial services"),
  "range": ("Souvent au-dessus de 5 M$ US/heure", "Often above $5M US/hour"),
  "note": ("ITIC classe la banque et la finance parmi les secteurs dont le coût horaire moyen dépasse 5 M$ US.", "ITIC ranks banking and finance among the sectors whose average hourly cost exceeds $5M US."),
  "src": 0},
 {"industry": ("Énergie et services publics", "Energy and utilities"),
  "range": ("≈ 2,48 M$ US/heure (estimation)", "≈ $2.48M US/hour (estimate)"),
  "note": ("Une estimation agrégée pour le secteur énergétique ; s'ajoutent des coûts non financiers lors d'une coupure prolongée.", "An aggregated estimate for the energy sector; a prolonged outage adds non-financial costs on top."),
  "src": 2},
 {"industry": ("Manufacture — automobile", "Manufacturing — automotive"),
  "range": ("Jusqu'à 2,3 M$ US/heure", "Up to $2.3M US/hour"),
  "note": ("Une ligne de production automobile à l'arrêt, selon le rapport Siemens True Cost of Downtime 2024.", "An idle automotive production line, per the Siemens True Cost of Downtime 2024 report."),
  "src": 3},
 {"industry": ("Manufacture — moyenne du secteur", "Manufacturing — sector average"),
  "range": ("≈ 260 000 $ US/heure", "≈ $260,000 US/hour"),
  "note": ("Moyenne toutes industries manufacturières confondues, selon Aberdeen Research.", "Average across all manufacturing sectors, per Aberdeen Research."),
  "src": 4},
 {"industry": ("Commerce de détail", "Retail"),
  "range": ("≈ 1,1 M$ US/heure (estimation)", "≈ $1.1M US/hour (estimate)"),
  "note": ("Estimation agrégée ; l'impact réel dépend fortement de la période (voir Amazon Prime Day ci-dessous).", "Aggregated estimate; the real impact depends heavily on timing (see Amazon Prime Day below)."),
  "src": 2},
 {"industry": ("Santé", "Healthcare"),
  "range": ("≈ 636 000 $ US/heure (estimation)", "≈ $636,000 US/hour (estimate)"),
  "note": ("Estimation agrégée pour le secteur ; l'incident Change Healthcare a montré un impact allant bien au-delà du financier.", "Aggregated estimate for the sector; the Change Healthcare incident showed impact reaching well beyond the financial."),
  "src": 2},
]

INCIDENTS = [
 {"name": ("Amazon — Prime Day 2018", "Amazon — Prime Day 2018"),
  "sector": ("Commerce de détail", "Retail"),
  "fact": ("Une panne de 63 à 75 minutes pendant l'événement de vente le plus chargé de l'année.", "A 63- to 75-minute outage during the year's busiest sales event."),
  "cost": ("72 M$ à 99 M$ US de ventes perdues, soit environ 1,2 M$ US par minute.", "$72M–$99M US in lost sales, about $1.2M US per minute."),
  "src": 5, "case": None},
 {"name": ("TSB — migration ratée", "TSB — botched migration"),
  "sector": ("Finance", "Finance"),
  "fact": ("Perturbation des services bancaires pendant plusieurs mois après une migration informatique.", "Banking services disrupted for months after an IT migration."),
  "cost": ("Amende de 48,65 M£ ; coûts totaux estimés à plus de 330 M£ selon la banque.", "£48.65m fine; total costs estimated by the bank at over £330m."),
  "src": None, "case": "case-studies/tsb-2018.html"},
 {"name": ("Colonial Pipeline — rançongiciel", "Colonial Pipeline — ransomware"),
  "sector": ("Énergie", "Energy"),
  "fact": ("Arrêt de 5 500 miles d'oléoduc pendant 6 jours, par précaution.", "5,500 miles of pipeline shut down for 6 days, as a precaution."),
  "cost": ("Rançon de 4,4 M$ US payée, plus des pénuries de carburant sur toute la côte Est.", "$4.4M US ransom paid, plus fuel shortages along the whole East Coast."),
  "src": None, "case": "case-studies/colonial-pipeline-2021.html"},
 {"name": ("Marks & Spencer — cyberattaque", "Marks & Spencer — cyberattack"),
  "sector": ("Commerce de détail", "Retail"),
  "fact": ("Commandes en ligne suspendues pendant environ 7 semaines.", "Online orders suspended for about 7 weeks."),
  "cost": ("Impact estimé à environ 300 M£ sur le bénéfice annuel.", "Impact estimated at about £300m off annual profit."),
  "src": None, "case": "case-studies/marks-and-spencer-2025.html"},
 {"name": ("Change Healthcare — rançongiciel", "Change Healthcare — ransomware"),
  "sector": ("Santé", "Healthcare"),
  "fact": ("Interruption des échanges de facturation touchant la majorité du système de santé américain.", "Billing exchange disruption affecting most of the US healthcare system."),
  "cost": ("Rançon de 22 M$ US payée, sans empêcher une seconde extorsion.", "$22M US ransom paid, without preventing a second extortion attempt."),
  "src": None, "case": "case-studies/change-healthcare-2024.html"},
 {"name": ("CrowdStrike / Delta — panne mondiale", "CrowdStrike / Delta — global outage"),
  "sector": ("Transport aérien", "Aviation"),
  "fact": ("Environ 8,5 millions de postes Windows en panne le même jour.", "About 8.5 million Windows devices down on the same day."),
  "cost": ("Delta indique environ 500 M$ US de coûts pour 5 jours de perturbation.", "Delta reports about $500M US in costs for 5 days of disruption."),
  "src": None, "case": "case-studies/crowdstrike-delta-2024.html"},
 {"name": ("Southwest Airlines — effondrement opérationnel", "Southwest Airlines — operational meltdown"),
  "sector": ("Transport aérien", "Aviation"),
  "fact": ("17 000 vols annulés sur environ 10 jours après une tempête hivernale, faute de logiciel de replanification capable de suivre.", "17,000 flights cancelled over about 10 days after a winter storm, because scheduling software couldn't keep up."),
  "cost": ("Plus de 1,1 G$ US de remboursements et de coûts, plus une amende de 140 M$ US.", "More than $1.1B US in refunds and costs, plus a $140M US fine."),
  "src": 6, "case": None},
]

SOURCES = [
 ("ITIC — 2024 Hourly Cost of Downtime Survey", "https://itic-corp.com/category/itic-reports-surveys/"),
 ("Atlassian — Cost of downtime (citing Gartner, 2014)", "https://www.atlassian.com/incident-management/kpis/cost-of-downtime"),
 ("Pingdom — Average Cost of Downtime per Industry", "https://www.pingdom.com/outages/average-cost-of-downtime-per-industry/"),
 ("Acronis — How unplanned OT downtime is draining industrial profits (citing Siemens, True Cost of Downtime 2024)", "https://www.acronis.com/en/blog/posts/how-unplanned-ot-downtime-is-silently-draining-industrial-profits/"),
 ("Verdantis — Unplanned Downtime Cost & Recovery (citing Aberdeen Research)", "https://www.verdantis.com/cost-of-downtime/"),
 ("TechCrunch — What Amazon lost (and made) on Amazon Prime Day", "https://techcrunch.com/2018/07/18/amazon-prime-day-outage-cost/"),
 ("CNN — Southwest hit by record $140 million fine for holiday service meltdown", "https://www.cnn.com/2023/12/18/business/southwest-fine-canceled-flights"),
]

METHOD_NOTE = ("Ces chiffres proviennent d'enquêtes et d'analyses publiques et varient selon la méthode de calcul retenue (revenu perdu, productivité, pénalités, image). Ils donnent un ordre de grandeur, pas une valeur applicable telle quelle à votre organisation : le meilleur moyen de connaître votre propre coût horaire est une analyse d'impact sur vos activités.",
               "These figures come from public surveys and analyses and vary with the calculation method used (lost revenue, productivity, penalties, reputation). They give an order of magnitude, not a number to apply directly to your organization: the best way to know your own hourly cost is a business impact analysis.")
