# Industry pages. Example engagements are illustrative scenarios, not client references.

def eng(t, ctx, work, out): return {"t": t, "ctx": ctx, "work": work, "out": out}

IND = [
 {
  "path": "what-we-do/industries/financial-services.html",
  "short": ("Services financiers", "Financial services"),
  "summary": ("Banques, assureurs, gestionnaires d'actifs et fintechs soumis à DORA, aux règles FCA/PRA ou au BSIF.", "Banks, insurers, asset managers and fintechs subject to DORA, FCA/PRA rules or OSFI."),
  "lede": ("Des attentes réglementaires fortes, des tiers critiques partout et une tolérance quasi nulle aux interruptions.", "High regulatory expectations, critical third parties everywhere and almost no tolerance for disruption."),
  "context": ("Les régulateurs financiers attendent désormais des preuves : services importants identifiés, seuils de tolérance fixés, scénarios testés et prestataires TIC sous contrôle. Nous aidons à transformer ces exigences en capacités vérifiables.",
              "Financial regulators now expect evidence: important services identified, impact tolerances set, scenarios tested and ICT providers under control. We help turn those requirements into verifiable capabilities."),
  "risks": [(("Prestataires TIC critiques", "Critical ICT providers"), ("Nuage, cœur bancaire, paiements : une panne chez un tiers devient la vôtre en quelques minutes, et souvent sans que vous en soyez informé avant vos propres clients. DORA et les règles FCA/PRA exigent désormais d'en apporter la preuve, pas seulement de l'affirmer.", "Cloud, core banking, payments: a third party's outage becomes yours within minutes, often before you even hear about it from anyone but your own customers. DORA and FCA/PRA rules now require proof of this, not just an assurance.")),
            (("Changements à haut risque", "High-risk change"), ("Les migrations et mises en production mal testées restent l'une des causes les plus fréquentes d'incidents majeurs, comme l'a montré la panne de TSB en 2018. Un changement à haut risque exige un plan de retour arrière aussi solide que le plan de déploiement lui-même.", "Poorly tested migrations and releases remain one of the most common causes of major incidents, as TSB's 2018 outage showed. A high-risk change needs a rollback plan as solid as the deployment plan itself.")),
            (("Fraude et rançongiciels", "Fraud and ransomware"), ("Les périodes de perturbation attirent les tentatives de fraude, car les contrôles habituels sont souvent relâchés pour rétablir le service au plus vite. Anticiper ce risque avant l'incident évite d'ajouter une crise financière à une crise opérationnelle.", "Periods of disruption attract fraud attempts, because normal controls are often loosened in the rush to restore service. Planning for this risk before the incident happens avoids stacking a financial crisis on top of an operational one."))],
  "regs": ["DORA", "FCA / PRA", "BSIF / OSFI B-13 · E-21", "SOC 2", "ISO 22301"],
  "engagements": [
    eng(("Analyse d'écart DORA", "DORA gap assessment"), ("Un assureur de taille moyenne doit démontrer sa conformité à DORA.", "A mid-sized insurer needs to demonstrate DORA compliance."),
        ("Revue des cinq piliers, registre des prestataires TIC, plan de tests et de déclaration d'incidents.", "Review of the five pillars, ICT third-party register, testing and incident reporting plan."),
        ("Feuille de route priorisée et dossier de preuves pour le régulateur.", "Prioritized roadmap and evidence pack for the regulator.")),
    eng(("Seuils de tolérance et scénarios", "Impact tolerances and scenarios"), ("Une banque britannique doit tester ses services d'affaires importants.", "A UK bank must test its important business services."),
        ("Cartographie des services, fixation des seuils, scénarios graves mais plausibles et exercices.", "Service mapping, tolerance setting, severe but plausible scenarios and exercises."),
        ("Auto-évaluation documentée et plan de correction.", "Documented self-assessment and remediation plan.")),
    eng(("Plans de sortie d'un fournisseur infonuagique", "Exit plans for a cloud provider"), ("Une fintech dépend d'un seul fournisseur infonuagique.", "A fintech relies on a single cloud provider."),
        ("Analyse de concentration, stratégie de sortie, reprise dans une autre région ou chez un autre fournisseur.", "Concentration analysis, exit strategy, recovery in another region or provider."),
        ("Plan de sortie testable et architecture cible.", "Testable exit plan and target architecture.")),
  ],
  "cases": ["case-studies/tsb-2018.html", "case-studies/crowdstrike-delta-2024.html"],
 },
 {
  "path": "what-we-do/industries/healthcare.html",
  "short": ("Santé", "Healthcare"),
  "summary": ("Cliniques, laboratoires et prestataires pour qui l'indisponibilité touche directement les patients.", "Clinics, labs and providers where downtime directly affects patients."),
  "lede": ("Quand les systèmes tombent, les soins doivent continuer.", "When systems go down, care has to continue."),
  "context": ("Le secteur de la santé est une cible privilégiée des rançongiciels et dépend de nombreux intermédiaires. Nous préparons les équipes cliniques et techniques à fonctionner en mode dégradé et à restaurer rapidement les systèmes essentiels.",
              "Healthcare is a favourite ransomware target and depends on many intermediaries. We prepare clinical and technical teams to work in degraded mode and to restore essential systems quickly."),
  "risks": [(("Rançongiciels", "Ransomware"), ("Dossiers patients, imagerie et prescriptions deviennent inaccessibles en quelques minutes, avec un effet direct sur les soins plutôt que seulement sur les affaires. C'est ce qui distingue la santé des autres secteurs : chaque minute de panne a un visage.", "Patient records, imaging and prescriptions become unavailable within minutes, with a direct effect on care rather than only on business. This is what sets healthcare apart from other sectors: every minute of downtime has a face attached to it.")),
            (("Intermédiaires critiques", "Critical intermediaries"), ("Facturation, pharmacie et laboratoires dépendent souvent d'un petit nombre d'intermédiaires partagés par tout le secteur, comme l'a montré l'incident de Change Healthcare. La perte d'un seul de ces intermédiaires peut immobiliser des milliers d'établissements en même temps.", "Billing, pharmacy and labs often depend on a small number of intermediaries shared across the whole sector, as the Change Healthcare incident showed. Losing just one of them can stall thousands of facilities at once.")),
            (("Données sensibles", "Sensitive data"), ("Les renseignements de santé exigent une protection renforcée, car leur sensibilité et leur valeur pour les attaquants dépassent celles de la plupart des autres données personnelles. Une fois divulgués, ils ne peuvent pas être changés comme un mot de passe.", "Health information requires stronger protection, because its sensitivity and its value to attackers exceed those of most other personal data. Once disclosed, it cannot be changed the way a password can."))],
  "regs": ["NIS2", "HIPAA", ("Loi 25 (Québec)", "Law 25 (Quebec)"), ("RGPD", "GDPR"), "ISO 27001"],
  "engagements": [
    eng(("Procédures de fonctionnement dégradé", "Downtime procedures"), ("Un réseau de cliniques n'a pas de procédure en cas de perte du dossier patient.", "A clinic network has no procedure if the patient record system is lost."),
        ("Ateliers avec le personnel clinique, formulaires papier, critères de déclenchement et de retour.", "Workshops with clinical staff, paper forms, criteria to invoke and to return."),
        ("Procédures testées et affichées dans chaque site.", "Tested procedures posted in every site.")),
    eng(("Exercice rançongiciel avec la direction médicale", "Ransomware exercise with medical leadership"), ("La direction veut savoir qui décide quoi en cas d'attaque.", "Leadership wants to know who decides what during an attack."),
        ("Exercice sur table sur trois jours simulés : isolement, patients, communication, rançon.", "Tabletop over three simulated days: containment, patients, communication, ransom."),
        ("Chaîne de décision clarifiée et plan d'action.", "Clarified decision chain and action plan.")),
    eng(("Validation de la restauration", "Restore validation"), ("Les sauvegardes du dossier patient et de l'imagerie n'ont jamais été restaurées en entier.", "Patient record and imaging backups have never been fully restored."),
        ("Test chronométré de restauration dans un environnement isolé.", "Timed restore test in an isolated environment."),
        ("RTO réel mesuré et corrections.", "Real RTO measured, and fixes.")),
  ],
  "cases": ["case-studies/change-healthcare-2024.html"],
 },
 {
  "path": "what-we-do/industries/technology-saas.html",
  "short": ("Technologie et SaaS", "Technology and SaaS"),
  "summary": ("Éditeurs de logiciels qui doivent démontrer leur résilience à leurs clients.", "Software companies that must demonstrate resilience to their customers."),
  "lede": ("Votre disponibilité est votre produit.", "Your availability is your product."),
  "context": ("Vos clients vous posent des questionnaires de sécurité, exigent un rapport SOC 2 et, dans la finance, vous considèrent comme un prestataire TIC critique au sens de DORA. Nous vous aidons à le prouver sans ralentir vos équipes.",
              "Your customers send security questionnaires, ask for a SOC 2 report and, in finance, treat you as a critical ICT provider under DORA. We help you prove it without slowing your teams down."),
  "risks": [(("Déploiements risqués", "Risky releases"), ("Une mise à jour défectueuse peut toucher tous vos clients au même instant, comme l'a montré la panne mondiale de CrowdStrike en 2024. Un déploiement progressif, avec des points d'arrêt clairs, limite un incident à une fraction de votre base plutôt qu'à sa totalité.", "One faulty update can hit every customer at the same instant, as the 2024 CrowdStrike outage showed worldwide. A staged rollout, with clear stop criteria, limits an incident to a fraction of your base rather than all of it.")),
            (("Région unique", "Single region"), ("Une panne régionale chez votre fournisseur infonuagique peut arrêter le service même si votre propre code n'a aucun défaut. S'appuyer sur une seule région revient à parier que ce fournisseur ne connaîtra jamais d'incident pendant toute la durée de vie de votre produit.", "A regional outage at your cloud provider can stop the service even when your own code has no defect. Relying on a single region is a bet that provider will never have an incident for the entire lifetime of your product.")),
            (("Exigences clients", "Customer requirements"), ("Questionnaires de sécurité, audits SOC 2 et clauses contractuelles de disponibilité deviennent une condition d'entrée chez vos plus gros clients, en particulier dans la finance. Y répondre rapidement et honnêtement est désormais un avantage commercial, pas seulement une contrainte.", "Security questionnaires, SOC 2 audits and contractual availability clauses are becoming a condition of entry with your largest customers, especially in finance. Answering them quickly and honestly is now a commercial advantage, not just a burden."))],
  "regs": ["SOC 2", "ISO 27001", "DORA", "NIS2"],
  "engagements": [
    eng(("Préparation SOC 2", "SOC 2 readiness"), ("Un éditeur doit obtenir son premier rapport SOC 2 Type II.", "A vendor needs its first SOC 2 Type II report."),
        ("Analyse d'écart, contrôles de disponibilité et de continuité, préparation des preuves.", "Gap analysis, availability and continuity controls, evidence preparation."),
        ("Programme de contrôles prêt pour l'auditeur.", "Control program ready for the auditor.")),
    eng(("Reprise multirégion", "Multi-region recovery"), ("Le service fonctionne dans une seule région infonuagique.", "The service runs in a single cloud region."),
        ("Conception de la reprise dans une seconde région, tests de bascule.", "Design of recovery in a second region, failover tests."),
        ("Architecture et procédures de bascule testées.", "Tested architecture and failover runbooks.")),
    eng(("Sécurité des mises en production", "Release safety"), ("Après la panne CrowdStrike, un client exige des garanties sur les mises à jour.", "After the CrowdStrike outage, a customer demands guarantees on updates."),
        ("Revue du déploiement progressif, des retours arrière et des indicateurs d'arrêt.", "Review of staged rollouts, rollbacks and stop criteria."),
        ("Politique de mise en production documentée pour les clients.", "Release policy documented for customers.")),
  ],
  "cases": ["case-studies/crowdstrike-delta-2024.html"],
 },
 {
  "path": "what-we-do/industries/manufacturing-transport.html",
  "short": ("Industrie, transport et logistique", "Manufacturing, transport and logistics"),
  "summary": ("Organisations où une panne informatique arrête la production, les livraisons ou les déplacements.", "Organizations where an IT outage stops production, deliveries or travel."),
  "lede": ("Continuer à produire et à livrer quand l'informatique s'arrête.", "Keep producing and delivering when IT stops."),
  "context": ("Usines, entrepôts et opérations de transport dépendent de systèmes informatiques et opérationnels étroitement liés. Nous aidons à comprendre ces dépendances et à préparer un mode manuel réaliste.",
              "Plants, warehouses and transport operations depend on tightly linked IT and operational systems. We help you understand those dependencies and prepare a realistic manual mode."),
  "risks": [(("Frontière TI/OT", "IT/OT boundary"), ("Une attaque qui ne touche que les systèmes informatiques peut tout de même forcer l'arrêt de la production, par précaution, comme l'a montré Norsk Hydro en 2019. Sans visibilité claire sur la frontière entre TI et OT, la décision la plus sûre est souvent de tout arrêter, au prix maximal.", "An attack that only hits IT systems can still force production to stop as a precaution, as Norsk Hydro showed in 2019. Without clear visibility into the IT/OT boundary, the safest decision is often to stop everything, at the highest possible cost.")),
            (("Annuaire et comptes à privilèges", "Directory and privileged accounts"), ("L'Active Directory est souvent la clé de toute l'infrastructure : qui y a accès administrateur peut, en théorie, tout atteindre. Sa perte ou sa compromission complique la reprise de chaque autre système qui en dépend, exactement ce qui a prolongé l'incident chez Norsk Hydro.", "Active Directory is often the key to the whole infrastructure: whoever has admin access there can, in principle, reach everything. Its loss or compromise complicates recovery for every other system that depends on it, exactly what drew out the Norsk Hydro incident.")),
            (("Rattrapage opérationnel", "Operational catch-up"), ("Une fois les systèmes rétablis, il reste encore les plannings, les équipages et les stocks à recalculer, un rattrapage qui peut durer plus longtemps que la panne elle-même. Delta et Southwest en ont fait l'expérience : le retour à la normale des systèmes n'est pas le retour à la normale des opérations.", "Once systems are back up, schedules, crews and stock still need to be recomputed, a catch-up that can last longer than the outage itself. Delta and Southwest both learned this: systems returning to normal is not the same as operations returning to normal."))],
  "regs": ["NIS2", "IEC 62443", "ISO 22301", "Cyber Essentials"],
  "engagements": [
    eng(("Cartographie TI/OT et mode manuel", "IT/OT mapping and manual mode"), ("Un fabricant ignore quelles lignes peuvent tourner sans l'informatique.", "A manufacturer doesn't know which lines can run without IT."),
        ("Cartographie des dépendances par ligne, procédures manuelles, exercice en usine.", "Dependency mapping by line, manual procedures, on-site exercise."),
        ("Mode dégradé documenté pour chaque site.", "Documented degraded mode for each site.")),
    eng(("Plan de reprise de l'Active Directory", "Active Directory recovery plan"), ("Aucune procédure pour reconstruire l'annuaire après une compromission.", "No procedure to rebuild the directory after a compromise."),
        ("Sauvegardes dédiées, forêt de reprise isolée, test de restauration.", "Dedicated backups, isolated recovery forest, restore test."),
        ("Procédure de reprise testée et délai mesuré.", "Tested recovery procedure and measured timing.")),
    eng(("Continuité des opérations de transport", "Transport operations continuity"), ("Un transporteur veut réduire le temps de rattrapage après une panne.", "A carrier wants to shorten catch-up time after an outage."),
        ("Scénario de perte des systèmes de planification, exercice et analyse des goulots.", "Scenario of losing scheduling systems, exercise and bottleneck analysis."),
        ("Plan de rattrapage et priorités de reprise.", "Catch-up plan and recovery priorities.")),
  ],
  "cases": ["case-studies/norsk-hydro-2019.html", "case-studies/crowdstrike-delta-2024.html"],
 },
 {
  "path": "what-we-do/industries/energy-utilities.html",
  "short": ("Énergie et services publics", "Energy and utilities"),
  "summary": ("Producteurs, réseaux et transporteurs d'énergie dont l'arrêt touche toute une région.", "Energy producers, grids and pipelines whose outage affects a whole region."),
  "lede": ("Des infrastructures critiques qui doivent tenir, même sous attaque.", "Critical infrastructure that must hold, even under attack."),
  "context": ("Dans l'énergie, la décision d'arrêter par précaution peut coûter autant que l'attaque elle-même. Nous aidons à définir à l'avance les critères de décision, à sécuriser les accès distants et à préparer la communication avec les autorités.",
              "In energy, a precautionary shutdown can cost as much as the attack itself. We help define decision criteria in advance, secure remote access and prepare communication with authorities."),
  "risks": [(("Accès distants", "Remote access"), ("Les accès VPN et les comptes inactifs restent des portes d'entrée fréquentes, comme l'a montré l'attaque de Colonial Pipeline en 2021. Un accès rarement utilisé, oublié par tous sauf un attaquant, suffit souvent à tout déclencher.", "VPN access and inactive accounts remain common ways in, as the Colonial Pipeline attack showed in 2021. An access point rarely used, forgotten by everyone except an attacker, is often enough to set everything off.")),
            (("Arrêt par précaution", "Precautionary shutdown"), ("Sans visibilité claire sur ce qui est réellement compromis, la réaction par défaut est d'arrêter tout, y compris ce qui n'est pas touché. C'est exactement ce choix, coûteux mais compréhensible, que Colonial Pipeline a dû faire faute de mieux savoir.", "Without clear visibility into what is actually compromised, the default reaction is to stop everything, including what isn't affected. That is exactly the costly but understandable choice Colonial Pipeline had to make, for lack of better information.")),
            (("Obligations de déclaration", "Reporting duties"), ("Les autorités exigent des déclarations rapides après un incident touchant une infrastructure critique, souvent dans des délais de quelques heures seulement. Improviser ces communications pendant la crise ajoute une charge que des modèles préparés à l'avance permettent d'éviter.", "Authorities require fast reporting after an incident affecting critical infrastructure, often within just a few hours. Improvising these communications during the crisis adds a burden that templates prepared in advance can avoid."))],
  "regs": ["NIS2", "NERC CIP", "IEC 62443", "NIST CSF 2.0"],
  "engagements": [
    eng(("Critères d'arrêt et de redémarrage", "Shutdown and restart criteria"), ("Un exploitant veut éviter un arrêt complet par précaution.", "An operator wants to avoid a full precautionary shutdown."),
        ("Analyse des dépendances TI/OT, arbres de décision, exercice avec les opérations.", "IT/OT dependency analysis, decision trees, exercise with operations."),
        ("Guide de décision validé par la direction.", "Decision guide approved by leadership.")),
    eng(("Durcissement des accès distants", "Remote access hardening"), ("Des prestataires se connectent aux installations par VPN.", "Contractors connect to facilities over VPN."),
        ("Inventaire des accès, MFA, revue des comptes, accès temporaires.", "Access inventory, MFA, account review, time-limited access."),
        ("Accès distants inventoriés et contrôlés.", "Inventoried and controlled remote access.")),
    eng(("Communication de crise réglementaire", "Regulatory crisis communication"), ("Aucun modèle de déclaration n'existe pour les autorités.", "No reporting templates exist for authorities."),
        ("Modèles de déclaration, contacts, simulation avec la direction.", "Reporting templates, contacts, simulation with leadership."),
        ("Dossier de communication prêt à l'emploi.", "Ready-to-use communication pack.")),
  ],
  "cases": ["case-studies/colonial-pipeline-2021.html", "case-studies/norsk-hydro-2019.html"],
 },
 {
  "path": "what-we-do/industries/retail.html",
  "short": ("Commerce de détail", "Retail"),
  "summary": ("Détaillants physiques et en ligne pour qui chaque heure d'arrêt se chiffre en ventes perdues.", "Store and online retailers for whom every hour down means lost sales."),
  "lede": ("Magasins ouverts, commandes en ligne, paiements : tout doit continuer.", "Open stores, online orders, payments: everything has to keep going."),
  "context": ("Le commerce de détail combine magasins, entrepôts, commerce électronique et paiements dans un système très interdépendant. Nous aidons à protéger les points d'entrée humains et à préparer un fonctionnement dégradé crédible.",
              "Retail combines stores, warehouses, e-commerce and payments in a tightly coupled system. We help protect the human entry points and prepare a credible degraded mode."),
  "risks": [(("Ingénierie sociale", "Social engineering"), ("Les centres de services et les prestataires externes sont ciblés par ingénierie sociale pour réinitialiser des accès ou des facteurs d'authentification, comme cela a été rapporté dans l'attaque contre Marks & Spencer en 2025. Une vérification d'identité solide à ce point d'entrée arrête souvent l'attaque avant qu'elle ne commence.", "Help desks and outside providers are targeted through social engineering to reset access or authentication factors, as reported in the 2025 Marks & Spencer attack. Strong identity verification at this entry point often stops the attack before it starts.")),
            (("Systèmes interdépendants", "Coupled systems"), ("Commandes, stocks et paiements sont si interdépendants qu'ils tombent presque toujours ensemble, jamais un seul à la fois. Un mode dégradé pensé après coup ne suffit pas : il doit être conçu, documenté et exercé avant que la panne ne survienne.", "Orders, stock and payments are so tightly coupled that they almost always go down together, never just one at a time. A degraded mode improvised on the spot isn't enough: it has to be designed, documented and rehearsed before the outage happens.")),
            (("Périodes de pointe", "Peak seasons"), ("Une panne pendant les fêtes ou une autre période de pointe coûte beaucoup plus cher qu'à n'importe quel autre moment de l'année, en ventes perdues comme en image. C'est aussi le moment où vos équipes ont le moins de marge pour improviser une réponse.", "An outage during the holidays or another peak period costs far more than at any other time of year, in lost sales and in reputation alike. It's also the moment your teams have the least room to improvise a response."))],
  "regs": ["PCI DSS", ("RGPD", "GDPR"), ("Loi 25 (Québec)", "Law 25 (Quebec)"), "NIST CSF 2.0"],
  "engagements": [
    eng(("Revue du centre de services", "Help desk review"), ("Un détaillant veut éviter une attaque par réinitialisation frauduleuse.", "A retailer wants to prevent a fraudulent-reset attack."),
        ("Revue des procédures de vérification d'identité, internes et chez le prestataire, test par scénario.", "Review of identity checks, in-house and at the provider, scenario test."),
        ("Procédures renforcées et formation des agents.", "Strengthened procedures and agent training.")),
    eng(("Mode dégradé en magasin", "Store degraded mode"), ("Les magasins ne savent pas vendre sans le système de caisse central.", "Stores can't sell without the central point-of-sale system."),
        ("Procédures de vente, de stock et de réapprovisionnement hors ligne.", "Offline sales, stock and replenishment procedures."),
        ("Guide magasin et exercice régional.", "Store guide and regional exercise.")),
    eng(("Résilience avant la haute saison", "Pre-peak resilience"), ("La direction veut être prête avant les fêtes.", "Leadership wants to be ready before the holidays."),
        ("Revue des points de défaillance, tests de charge et de reprise, exercice de crise.", "Single-point-of-failure review, load and recovery tests, crisis exercise."),
        ("Plan de préparation et cellule de crise prête.", "Readiness plan and crisis team ready.")),
  ],
  "cases": ["case-studies/marks-and-spencer-2025.html"],
 },
 {
  "path": "what-we-do/industries/professional-services.html",
  "short": ("Services professionnels", "Professional services"),
  "summary": ("Cabinets juridiques, comptables et de conseil qui protègent des données clients sensibles.", "Law, accounting and consulting firms protecting sensitive client data."),
  "lede": ("La confiance de vos clients repose sur la confidentialité et la disponibilité.", "Your clients' trust rests on confidentiality and availability."),
  "context": ("Les cabinets reposent sur leur messagerie, leurs documents et leurs outils collaboratifs, et doivent répondre à des questionnaires de sécurité de plus en plus exigeants. Nous aidons à sécuriser l'essentiel et à le démontrer.",
              "Firms run on email, documents and collaboration tools, and face increasingly demanding security questionnaires. We help secure what matters and prove it."),
  "risks": [(("Compromission de messagerie", "Email compromise"), ("Une messagerie compromise ouvre la voie à la fraude au virement et à la fuite de documents clients confidentiels, souvent sans qu'aucune alerte technique ne se déclenche. Pour un cabinet, la confiance perdue peut coûter plus cher que l'incident lui-même.", "A compromised mailbox opens the door to payment fraud and leaks of confidential client documents, often without any technical alert ever firing. For a firm, the trust lost can cost more than the incident itself.")),
            (("Données SaaS", "SaaS data"), ("Documents et courriels sont rarement sauvegardés en dehors de la plateforme collaborative elle-même, ce qui laisse peu de recours en cas de suppression accidentelle ou malveillante. Une copie indépendante, testée, est la seule vraie garantie de pouvoir tout récupérer.", "Documents and email are rarely backed up outside the collaboration platform itself, leaving little recourse if something is deleted by accident or by an attacker. An independent, tested copy is the only real guarantee that everything can be recovered.")),
            (("Exigences clients", "Client requirements"), ("Les questionnaires de sécurité et les clauses contractuelles se multiplient à mesure que les clients eux-mêmes font face à des exigences réglementaires plus strictes. Une bibliothèque de réponses à jour transforme cette charge en formalité plutôt qu'en projet à chaque fois.", "Security questionnaires and contractual clauses are multiplying as clients themselves face stricter regulatory requirements. An up-to-date answer library turns this burden into a formality rather than a fresh project every time."))],
  "regs": ["ISO 27001", ("RGPD", "GDPR"), ("Loi 25 (Québec)", "Law 25 (Quebec)"), "Cyber Essentials"],
  "engagements": [
    eng(("Sauvegarde Microsoft 365", "Microsoft 365 backup"), ("Un cabinet n'a aucune copie indépendante de ses courriels et documents.", "A firm has no independent copy of its email and documents."),
        ("Choix de la solution, politique de conservation, test de restauration.", "Solution selection, retention policy, restore test."),
        ("Sauvegarde indépendante opérationnelle et testée.", "Independent backup in place and tested.")),
    eng(("Réponse aux incidents et notification", "Incident response and notification"), ("Le cabinet ne sait pas quand et comment prévenir ses clients.", "The firm doesn't know when and how to notify clients."),
        ("Plan de réponse, critères de notification, modèles de messages.", "Response plan, notification criteria, message templates."),
        ("Plan prêt à l'emploi, exercé avec les associés.", "Ready-to-use plan, rehearsed with partners.")),
    eng(("Questionnaires de sécurité", "Security questionnaires"), ("Les demandes des clients prennent des semaines à traiter.", "Client requests take weeks to answer."),
        ("Bibliothèque de réponses, preuves et politiques de référence.", "Answer library, evidence and reference policies."),
        ("Délai de réponse réduit et discours cohérent.", "Shorter turnaround and consistent answers.")),
  ],
  "cases": [],
 },
 {
  "path": "what-we-do/industries/public-sector.html",
  "short": ("Secteur public et OBNL", "Public sector and non-profits"),
  "summary": ("Organismes aux ressources limitées qui doivent maintenir des services essentiels.", "Organizations with limited resources that must keep essential services running."),
  "lede": ("Des services essentiels à maintenir, avec des moyens comptés.", "Essential services to maintain, with limited means."),
  "context": ("Les organismes publics et communautaires sont de plus en plus ciblés, souvent avec peu de ressources spécialisées. Nous priorisons les mesures les plus efficaces pour le budget disponible.",
              "Public and community organizations are increasingly targeted, often with few specialist resources. We prioritize the most effective measures for the available budget."),
  "risks": [(("Budgets limités", "Limited budgets"), ("Avec un budget limité, il faut choisir les mesures qui réduisent le plus le risque par dollar investi, plutôt que de viser l'exhaustivité. Quelques mesures bien choisies protègent souvent mieux qu'un programme ambitieux jamais complété.", "With a limited budget, you have to choose the measures that reduce risk the most per dollar spent, rather than aim for completeness. A few well-chosen measures often protect better than an ambitious program that never gets finished.")),
            (("Services aux citoyens", "Services to citizens"), ("Une interruption touche directement la population que l'organisme sert, souvent des personnes qui n'ont pas d'autre recours en cas de panne prolongée. Cette responsabilité justifie de protéger les services essentiels même quand le budget de sécurité reste modeste.", "An interruption directly affects the public the organization serves, often people who have no other option during a prolonged outage. That responsibility justifies protecting essential services even when the security budget stays modest.")),
            (("Prestataires externes", "External providers"), ("Beaucoup de services publics reposent sur des fournisseurs externes, souvent choisis au plus bas prix sans exigence de continuité dans l'appel d'offres. Ajouter ces exigences dès le contrat coûte peu et évite d'en payer le prix fort lors d'une panne.", "Many public services rely on external suppliers, often chosen at the lowest price with no continuity requirement in the tender. Adding those requirements at contract stage costs little and avoids paying dearly for their absence during an outage."))],
  "regs": ["NIS2", "Cyber Essentials", ("Loi 25 (Québec)", "Law 25 (Quebec)"), "NIST CSF 2.0"],
  "engagements": [
    eng(("Continuité des services essentiels", "Essential service continuity"), ("Une municipalité veut savoir quels services maintenir en priorité.", "A municipality wants to know which services to keep first."),
        ("Analyse d'impact, plans par service, exercice avec les élus et gestionnaires.", "Impact analysis, service plans, exercise with officials and managers."),
        ("Priorités de reprise validées et plans à jour.", "Approved recovery priorities and current plans.")),
    eng(("Préparation aux rançongiciels à petit budget", "Ransomware readiness on a small budget"), ("Un organisme sans équipe de sécurité dédiée.", "An organization without a dedicated security team."),
        ("Évaluation rapide, dix mesures prioritaires, accompagnement à la mise en œuvre.", "Quick assessment, ten priority measures, implementation support."),
        ("Réduction mesurable du risque en quelques mois.", "Measurable risk reduction within months.")),
    eng(("Dépendances aux fournisseurs", "Supplier dependencies"), ("Des services clés sont externalisés sans clauses de continuité.", "Key services are outsourced without continuity clauses."),
        ("Cartographie, clauses types, exigences de reprise pour les appels d'offres.", "Mapping, model clauses, recovery requirements for tenders."),
        ("Contrats et appels d'offres renforcés.", "Stronger contracts and tenders.")),
  ],
  "cases": ["case-studies/crowdstrike-delta-2024.html"],
 },
]
