# Industry pages. Example engagements are illustrative scenarios, not client references.

def eng(t, ctx, work, out): return {"t": t, "ctx": ctx, "work": work, "out": out}

IND = [
 {
  "path": "what-we-do/industries/financial-services.html",
  "short": ("Services financiers", "Financial services"),
  "summary": ("Banques, assureurs, gestionnaires d'actifs et fintechs soumis à DORA, aux règles FCA/PRA ou au BSIF.", "Banks, insurers, asset managers and fintechs subject to DORA, FCA/PRA rules or OSFI."),
  "lede": ("Des attentes réglementaires fortes, des tiers critiques partout et une tolérance quasi nulle aux interruptions.", "High regulatory expectations, critical third parties everywhere and almost no tolerance for disruption."),
  "context": ("Les régulateurs financiers attendent désormais des preuves : services importants identifiés, seuils de tolérance fixés, scénarios testés et prestataires TIC sous contrôle. Nous aidons à transformer ces exigences en capacités vérifiables.",
              "Financial regulators now expect evidence: important services identified, impact tolerances set, scenarios tested and ICT providers under control. We help turn those requirements into verifiable capabilities."),
  "risks": [(("Prestataires TIC critiques", "Critical ICT providers"), ("Nuage, cœur bancaire, paiements : une panne chez un tiers devient la vôtre.", "Cloud, core banking, payments: a third party's outage becomes yours.")),
            (("Changements à haut risque", "High-risk change"), ("Migrations et mises en production mal testées, comme l'a montré TSB.", "Poorly tested migrations and releases, as TSB showed.")),
            (("Fraude et rançongiciels", "Fraud and ransomware"), ("Les périodes de perturbation attirent les tentatives d'escroquerie.", "Periods of disruption attract fraud attempts."))],
  "regs": ["DORA", "FCA / PRA", "BSIF / OSFI B-13 · E-21", "SOC 2", "ISO 22301"],
  "engagements": [
    eng(("Analyse d'écart DORA", "DORA gap assessment"), ("Un assureur de taille moyenne doit démontrer sa conformité à DORA.", "A mid-sized insurer needs to demonstrate DORA compliance."),
        ("Revue des cinq piliers, registre des prestataires TIC, plan de tests et de déclaration d'incidents.", "Review of the five pillars, ICT third-party register, testing and incident reporting plan."),
        ("Feuille de route priorisée et dossier de preuves pour le régulateur.", "Prioritized roadmap and evidence pack for the regulator.")),
    eng(("Seuils de tolérance et scénarios", "Impact tolerances and scenarios"), ("Une banque britannique doit tester ses services d'affaires importants.", "A UK bank must test its important business services."),
        ("Cartographie des services, fixation des seuils, scénarios graves mais plausibles et exercices.", "Service mapping, tolerance setting, severe but plausible scenarios and exercises."),
        ("Auto-évaluation documentée et plan de correction.", "Documented self-assessment and remediation plan.")),
    eng(("Plans de sortie d'un fournisseur infonuagique", "Exit plans for a cloud provider"), ("Une fintech dépend d'un seul fournisseur infonuagique.", "A fintech relies on a single cloud provider."),
        ("Analyse de concentration, stratégie de sortie, reprise dans une autre région ou chez un autre fournisseur.", "Concentration analysis, exit strategy, recovery in another region or provider."),
        ("Plan de sortie testable et architecture cible.", "Testable exit plan and target architecture.")),
  ],
  "cases": ["case-studies/tsb-2018.html", "case-studies/crowdstrike-delta-2024.html"],
 },
 {
  "path": "what-we-do/industries/healthcare.html",
  "short": ("Santé", "Healthcare"),
  "summary": ("Cliniques, laboratoires et prestataires pour qui l'indisponibilité touche directement les patients.", "Clinics, labs and providers where downtime directly affects patients."),
  "lede": ("Quand les systèmes tombent, les soins doivent continuer.", "When systems go down, care has to continue."),
  "context": ("Le secteur de la santé est une cible privilégiée des rançongiciels et dépend de nombreux intermédiaires. Nous préparons les équipes cliniques et techniques à fonctionner en mode dégradé et à restaurer rapidement les systèmes essentiels.",
              "Healthcare is a favourite ransomware target and depends on many intermediaries. We prepare clinical and technical teams to work in degraded mode and to restore essential systems quickly."),
  "risks": [(("Rançongiciels", "Ransomware"), ("Dossiers patients, imagerie et prescriptions inaccessibles.", "Patient records, imaging and prescriptions become unavailable.")),
            (("Intermédiaires critiques", "Critical intermediaries"), ("Facturation, pharmacie et laboratoires dépendent de tiers.", "Billing, pharmacy and labs depend on third parties.")),
            (("Données sensibles", "Sensitive data"), ("Les renseignements de santé exigent une protection renforcée.", "Health information requires stronger protection."))],
  "regs": ["NIS2", "HIPAA", ("Loi 25 (Québec)", "Law 25 (Quebec)"), ("RGPD", "GDPR"), "ISO 27001"],
  "engagements": [
    eng(("Procédures de fonctionnement dégradé", "Downtime procedures"), ("Un réseau de cliniques n'a pas de procédure en cas de perte du dossier patient.", "A clinic network has no procedure if the patient record system is lost."),
        ("Ateliers avec le personnel clinique, formulaires papier, critères de déclenchement et de retour.", "Workshops with clinical staff, paper forms, criteria to invoke and to return."),
        ("Procédures testées et affichées dans chaque site.", "Tested procedures posted in every site.")),
    eng(("Exercice rançongiciel avec la direction médicale", "Ransomware exercise with medical leadership"), ("La direction veut savoir qui décide quoi en cas d'attaque.", "Leadership wants to know who decides what during an attack."),
        ("Exercice sur table sur trois jours simulés : isolement, patients, communication, rançon.", "Tabletop over three simulated days: containment, patients, communication, ransom."),
        ("Chaîne de décision clarifiée et plan d'action.", "Clarified decision chain and action plan.")),
    eng(("Validation de la restauration", "Restore validation"), ("Les sauvegardes du dossier patient et de l'imagerie n'ont jamais été restaurées en entier.", "Patient record and imaging backups have never been fully restored."),
        ("Test chronométré de restauration dans un environnement isolé.", "Timed restore test in an isolated environment."),
        ("RTO réel mesuré et corrections.", "Real RTO measured, and fixes.")),
  ],
  "cases": ["case-studies/change-healthcare-2024.html"],
 },
 {
  "path": "what-we-do/industries/technology-saas.html",
  "short": ("Technologie et SaaS", "Technology and SaaS"),
  "summary": ("Éditeurs de logiciels qui doivent démontrer leur résilience à leurs clients.", "Software companies that must demonstrate resilience to their customers."),
  "lede": ("Votre disponibilité est votre produit.", "Your availability is your product."),
  "context": ("Vos clients vous posent des questionnaires de sécurité, exigent un rapport SOC 2 et, dans la finance, vous considèrent comme un prestataire TIC critique au sens de DORA. Nous vous aidons à le prouver sans ralentir vos équipes.",
              "Your customers send security questionnaires, ask for a SOC 2 report and, in finance, treat you as a critical ICT provider under DORA. We help you prove it without slowing your teams down."),
  "risks": [(("Déploiements risqués", "Risky releases"), ("Une mise à jour défectueuse peut toucher tous les clients à la fois.", "One faulty update can hit every customer at once.")),
            (("Région unique", "Single region"), ("Une panne régionale du fournisseur infonuagique arrête le service.", "A regional cloud outage stops the service.")),
            (("Exigences clients", "Customer requirements"), ("Questionnaires, audits et clauses contractuelles de disponibilité.", "Questionnaires, audits and availability clauses."))],
  "regs": ["SOC 2", "ISO 27001", "DORA", "NIS2"],
  "engagements": [
    eng(("Préparation SOC 2", "SOC 2 readiness"), ("Un éditeur doit obtenir son premier rapport SOC 2 Type II.", "A vendor needs its first SOC 2 Type II report."),
        ("Analyse d'écart, contrôles de disponibilité et de continuité, préparation des preuves.", "Gap analysis, availability and continuity controls, evidence preparation."),
        ("Programme de contrôles prêt pour l'auditeur.", "Control program ready for the auditor.")),
    eng(("Reprise multirégion", "Multi-region recovery"), ("Le service fonctionne dans une seule région infonuagique.", "The service runs in a single cloud region."),
        ("Conception de la reprise dans une seconde région, tests de bascule.", "Design of recovery in a second region, failover tests."),
        ("Architecture et procédures de bascule testées.", "Tested architecture and failover runbooks.")),
    eng(("Sécurité des mises en production", "Release safety"), ("Après la panne CrowdStrike, un client exige des garanties sur les mises à jour.", "After the CrowdStrike outage, a customer demands guarantees on updates."),
        ("Revue du déploiement progressif, des retours arrière et des indicateurs d'arrêt.", "Review of staged rollouts, rollbacks and stop criteria."),
        ("Politique de mise en production documentée pour les clients.", "Release policy documented for customers.")),
  ],
  "cases": ["case-studies/crowdstrike-delta-2024.html"],
 },
 {
  "path": "what-we-do/industries/manufacturing-transport.html",
  "short": ("Industrie, transport et logistique", "Manufacturing, transport and logistics"),
  "summary": ("Organisations où une panne informatique arrête la production, les livraisons ou les déplacements.", "Organizations where an IT outage stops production, deliveries or travel."),
  "lede": ("Continuer à produire et à livrer quand l'informatique s'arrête.", "Keep producing and delivering when IT stops."),
  "context": ("Usines, entrepôts et opérations de transport dépendent de systèmes informatiques et opérationnels étroitement liés. Nous aidons à comprendre ces dépendances et à préparer un mode manuel réaliste.",
              "Plants, warehouses and transport operations depend on tightly linked IT and operational systems. We help you understand those dependencies and prepare a realistic manual mode."),
  "risks": [(("Frontière TI/OT", "IT/OT boundary"), ("Une attaque sur l'informatique peut forcer l'arrêt de la production.", "An attack on IT can force production to stop.")),
            (("Annuaire et comptes à privilèges", "Directory and privileged accounts"), ("L'Active Directory est souvent la clé de toute l'infrastructure.", "Active Directory is often the key to the whole infrastructure.")),
            (("Rattrapage opérationnel", "Operational catch-up"), ("Plannings, équipages et stocks à recalculer après la panne.", "Schedules, crews and stock to recompute after the outage."))],
  "regs": ["NIS2", "IEC 62443", "ISO 22301", "Cyber Essentials"],
  "engagements": [
    eng(("Cartographie TI/OT et mode manuel", "IT/OT mapping and manual mode"), ("Un fabricant ignore quelles lignes peuvent tourner sans l'informatique.", "A manufacturer doesn't know which lines can run without IT."),
        ("Cartographie des dépendances par ligne, procédures manuelles, exercice en usine.", "Dependency mapping by line, manual procedures, on-site exercise."),
        ("Mode dégradé documenté pour chaque site.", "Documented degraded mode for each site.")),
    eng(("Plan de reprise de l'Active Directory", "Active Directory recovery plan"), ("Aucune procédure pour reconstruire l'annuaire après une compromission.", "No procedure to rebuild the directory after a compromise."),
        ("Sauvegardes dédiées, forêt de reprise isolée, test de restauration.", "Dedicated backups, isolated recovery forest, restore test."),
        ("Procédure de reprise testée et délai mesuré.", "Tested recovery procedure and measured timing.")),
    eng(("Continuité des opérations de transport", "Transport operations continuity"), ("Un transporteur veut réduire le temps de rattrapage après une panne.", "A carrier wants to shorten catch-up time after an outage."),
        ("Scénario de perte des systèmes de planification, exercice et analyse des goulots.", "Scenario of losing scheduling systems, exercise and bottleneck analysis."),
        ("Plan de rattrapage et priorités de reprise.", "Catch-up plan and recovery priorities.")),
  ],
  "cases": ["case-studies/norsk-hydro-2019.html", "case-studies/crowdstrike-delta-2024.html"],
 },
 {
  "path": "what-we-do/industries/energy-utilities.html",
  "short": ("Énergie et services publics", "Energy and utilities"),
  "summary": ("Producteurs, réseaux et transporteurs d'énergie dont l'arrêt touche toute une région.", "Energy producers, grids and pipelines whose outage affects a whole region."),
  "lede": ("Des infrastructures critiques qui doivent tenir, même sous attaque.", "Critical infrastructure that must hold, even under attack."),
  "context": ("Dans l'énergie, la décision d'arrêter par précaution peut coûter autant que l'attaque elle-même. Nous aidons à définir à l'avance les critères de décision, à sécuriser les accès distants et à préparer la communication avec les autorités.",
              "In energy, a precautionary shutdown can cost as much as the attack itself. We help define decision criteria in advance, secure remote access and prepare communication with authorities."),
  "risks": [(("Accès distants", "Remote access"), ("VPN et comptes inactifs restent des portes d'entrée fréquentes.", "VPNs and inactive accounts remain common ways in.")),
            (("Arrêt par précaution", "Precautionary shutdown"), ("Sans visibilité, on arrête tout, même ce qui n'est pas touché.", "Without visibility, everything stops, even what isn't affected.")),
            (("Obligations de déclaration", "Reporting duties"), ("Les autorités exigent des déclarations rapides.", "Authorities require fast reporting."))],
  "regs": ["NIS2", "NERC CIP", "IEC 62443", "NIST CSF 2.0"],
  "engagements": [
    eng(("Critères d'arrêt et de redémarrage", "Shutdown and restart criteria"), ("Un exploitant veut éviter un arrêt complet par précaution.", "An operator wants to avoid a full precautionary shutdown."),
        ("Analyse des dépendances TI/OT, arbres de décision, exercice avec les opérations.", "IT/OT dependency analysis, decision trees, exercise with operations."),
        ("Guide de décision validé par la direction.", "Decision guide approved by leadership.")),
    eng(("Durcissement des accès distants", "Remote access hardening"), ("Des prestataires se connectent aux installations par VPN.", "Contractors connect to facilities over VPN."),
        ("Inventaire des accès, MFA, revue des comptes, accès temporaires.", "Access inventory, MFA, account review, time-limited access."),
        ("Accès distants inventoriés et contrôlés.", "Inventoried and controlled remote access.")),
    eng(("Communication de crise réglementaire", "Regulatory crisis communication"), ("Aucun modèle de déclaration n'existe pour les autorités.", "No reporting templates exist for authorities."),
        ("Modèles de déclaration, contacts, simulation avec la direction.", "Reporting templates, contacts, simulation with leadership."),
        ("Dossier de communication prêt à l'emploi.", "Ready-to-use communication pack.")),
  ],
  "cases": ["case-studies/colonial-pipeline-2021.html", "case-studies/norsk-hydro-2019.html"],
 },
 {
  "path": "what-we-do/industries/retail.html",
  "short": ("Commerce de détail", "Retail"),
  "summary": ("Détaillants physiques et en ligne pour qui chaque heure d'arrêt se chiffre en ventes perdues.", "Store and online retailers for whom every hour down means lost sales."),
  "lede": ("Magasins ouverts, commandes en ligne, paiements : tout doit continuer.", "Open stores, online orders, payments: everything has to keep going."),
  "context": ("Le commerce de détail combine magasins, entrepôts, commerce électronique et paiements dans un système très interdépendant. Nous aidons à protéger les points d'entrée humains et à préparer un fonctionnement dégradé crédible.",
              "Retail combines stores, warehouses, e-commerce and payments in a tightly coupled system. We help protect the human entry points and prepare a credible degraded mode."),
  "risks": [(("Ingénierie sociale", "Social engineering"), ("Centres de services et prestataires ciblés pour réinitialiser des accès.", "Help desks and providers targeted to reset access.")),
            (("Systèmes interdépendants", "Coupled systems"), ("Commandes, stocks et paiements tombent ensemble.", "Orders, stock and payments go down together.")),
            (("Périodes de pointe", "Peak seasons"), ("Une panne pendant les fêtes coûte beaucoup plus cher.", "An outage during the holidays costs far more."))],
  "regs": ["PCI DSS", ("RGPD", "GDPR"), ("Loi 25 (Québec)", "Law 25 (Quebec)"), "NIST CSF 2.0"],
  "engagements": [
    eng(("Revue du centre de services", "Help desk review"), ("Un détaillant veut éviter une attaque par réinitialisation frauduleuse.", "A retailer wants to prevent a fraudulent-reset attack."),
        ("Revue des procédures de vérification d'identité, internes et chez le prestataire, test par scénario.", "Review of identity checks, in-house and at the provider, scenario test."),
        ("Procédures renforcées et formation des agents.", "Strengthened procedures and agent training.")),
    eng(("Mode dégradé en magasin", "Store degraded mode"), ("Les magasins ne savent pas vendre sans le système de caisse central.", "Stores can't sell without the central point-of-sale system."),
        ("Procédures de vente, de stock et de réapprovisionnement hors ligne.", "Offline sales, stock and replenishment procedures."),
        ("Guide magasin et exercice régional.", "Store guide and regional exercise.")),
    eng(("Résilience avant la haute saison", "Pre-peak resilience"), ("La direction veut être prête avant les fêtes.", "Leadership wants to be ready before the holidays."),
        ("Revue des points de défaillance, tests de charge et de reprise, exercice de crise.", "Single-point-of-failure review, load and recovery tests, crisis exercise."),
        ("Plan de préparation et cellule de crise prête.", "Readiness plan and crisis team ready.")),
  ],
  "cases": ["case-studies/marks-and-spencer-2025.html"],
 },
 {
  "path": "what-we-do/industries/professional-services.html",
  "short": ("Services professionnels", "Professional services"),
  "summary": ("Cabinets juridiques, comptables et de conseil qui protègent des données clients sensibles.", "Law, accounting and consulting firms protecting sensitive client data."),
  "lede": ("La confiance de vos clients repose sur la confidentialité et la disponibilité.", "Your clients' trust rests on confidentiality and availability."),
  "context": ("Les cabinets reposent sur leur messagerie, leurs documents et leurs outils collaboratifs, et doivent répondre à des questionnaires de sécurité de plus en plus exigeants. Nous aidons à sécuriser l'essentiel et à le démontrer.",
              "Firms run on email, documents and collaboration tools, and face increasingly demanding security questionnaires. We help secure what matters and prove it."),
  "risks": [(("Compromission de messagerie", "Email compromise"), ("Fraude au virement et fuite de documents clients.", "Payment fraud and client document leaks.")),
            (("Données SaaS", "SaaS data"), ("Documents et courriels rarement sauvegardés hors de la plateforme.", "Documents and email rarely backed up outside the platform.")),
            (("Exigences clients", "Client requirements"), ("Questionnaires et clauses de sécurité dans les contrats.", "Questionnaires and security clauses in contracts."))],
  "regs": ["ISO 27001", ("RGPD", "GDPR"), ("Loi 25 (Québec)", "Law 25 (Quebec)"), "Cyber Essentials"],
  "engagements": [
    eng(("Sauvegarde Microsoft 365", "Microsoft 365 backup"), ("Un cabinet n'a aucune copie indépendante de ses courriels et documents.", "A firm has no independent copy of its email and documents."),
        ("Choix de la solution, politique de conservation, test de restauration.", "Solution selection, retention policy, restore test."),
        ("Sauvegarde indépendante opérationnelle et testée.", "Independent backup in place and tested.")),
    eng(("Réponse aux incidents et notification", "Incident response and notification"), ("Le cabinet ne sait pas quand et comment prévenir ses clients.", "The firm doesn't know when and how to notify clients."),
        ("Plan de réponse, critères de notification, modèles de messages.", "Response plan, notification criteria, message templates."),
        ("Plan prêt à l'emploi, exercé avec les associés.", "Ready-to-use plan, rehearsed with partners.")),
    eng(("Questionnaires de sécurité", "Security questionnaires"), ("Les demandes des clients prennent des semaines à traiter.", "Client requests take weeks to answer."),
        ("Bibliothèque de réponses, preuves et politiques de référence.", "Answer library, evidence and reference policies."),
        ("Délai de réponse réduit et discours cohérent.", "Shorter turnaround and consistent answers.")),
  ],
  "cases": [],
 },
 {
  "path": "what-we-do/industries/public-sector.html",
  "short": ("Secteur public et OBNL", "Public sector and non-profits"),
  "summary": ("Organismes aux ressources limitées qui doivent maintenir des services essentiels.", "Organizations with limited resources that must keep essential services running."),
  "lede": ("Des services essentiels à maintenir, avec des moyens comptés.", "Essential services to maintain, with limited means."),
  "context": ("Les organismes publics et communautaires sont de plus en plus ciblés, souvent avec peu de ressources spécialisées. Nous priorisons les mesures les plus efficaces pour le budget disponible.",
              "Public and community organizations are increasingly targeted, often with few specialist resources. We prioritize the most effective measures for the available budget."),
  "risks": [(("Budgets limités", "Limited budgets"), ("Il faut choisir les mesures qui réduisent le plus le risque.", "You have to choose the measures that reduce risk the most.")),
            (("Services aux citoyens", "Services to citizens"), ("Une interruption touche directement la population.", "An interruption directly affects the public.")),
            (("Prestataires externes", "External providers"), ("Beaucoup de services reposent sur des fournisseurs.", "Many services rely on suppliers."))],
  "regs": ["NIS2", "Cyber Essentials", ("Loi 25 (Québec)", "Law 25 (Quebec)"), "NIST CSF 2.0"],
  "engagements": [
    eng(("Continuité des services essentiels", "Essential service continuity"), ("Une municipalité veut savoir quels services maintenir en priorité.", "A municipality wants to know which services to keep first."),
        ("Analyse d'impact, plans par service, exercice avec les élus et gestionnaires.", "Impact analysis, service plans, exercise with officials and managers."),
        ("Priorités de reprise validées et plans à jour.", "Approved recovery priorities and current plans.")),
    eng(("Préparation aux rançongiciels à petit budget", "Ransomware readiness on a small budget"), ("Un organisme sans équipe de sécurité dédiée.", "An organization without a dedicated security team."),
        ("Évaluation rapide, dix mesures prioritaires, accompagnement à la mise en œuvre.", "Quick assessment, ten priority measures, implementation support."),
        ("Réduction mesurable du risque en quelques mois.", "Measurable risk reduction within months.")),
    eng(("Dépendances aux fournisseurs", "Supplier dependencies"), ("Des services clés sont externalisés sans clauses de continuité.", "Key services are outsourced without continuity clauses."),
        ("Cartographie, clauses types, exigences de reprise pour les appels d'offres.", "Mapping, model clauses, recovery requirements for tenders."),
        ("Contrats et appels d'offres renforcés.", "Stronger contracts and tenders.")),
  ],
  "cases": ["case-studies/crowdstrike-delta-2024.html"],
 },
]
